### ISSUE TITLE
Prevent issues when OIDC is enabled with double emails

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#1199]
If you enable OIDC we might need to switch off regular logins (and remove accounts created that way). We need to think this through first.

**Comment by sergei-maertens** [comment]
This will need some more refinement/information before I can pick this up.

**Comment by joeribekker** [comment]
This ticket was made because an OIDC accounts can attempt to set the same email on the User object as an existing User object, causing you can never login with OIDC as long as that regular User object exists. I think we should simply disable regular users/user-creation when OIDC is used.

**Comment by sergei-maertens** [comment]
Refined a bit further - technical approaches involve a bit of work that isn't ideal nor elegant and the situations really are edge cases that don't really warrant all the effort.

The approach we decided on is to:

1. Catch duplicate e-mail violations explicitly and show this as error message to the end user trying to log in. They can then contact an administrator to edit/fix/delete the local user.
2. Document this particular situation in the known auth issues documentation (and link to it from the error message?)
3. Catch generic auth errors and display an error (rather than just showing the login screen again)
