### ISSUE TITLE
SDK Summary page fails

### ISSUE THREAD

**Issue by Bartvaderkin** [open-formulieren/open-forms#1226]
Part of a longer Taiga ticket (with other issues): 292 (the Taiga issue is about file uploads but apparently a similar fail problem also happens on certain forms without file component). See ticket for form.

My JS debugger gives this error in React:

`Error: Minified React error #152; visit https://reactjs.org/docs/error-decoder.html?invariant=152&args[]=radio for the full message or use the non-minified dev environment for full errors and additional helpful warnings.`

(when I follow the URL it says "rgs[radio](...): Nothing was returned from render. This usually means a return statement is missing. Or, to render nothing, return null.")

**Comment by SilviaAmAm** [comment]
Looking at the form bezwaar-gemeentelijke-belastingen and it seems that here the problem is 'selectboxes'.

If the selectboxes are within a hidden component, they have a value of `undefined`, which makes the summary page fail. So I guess https://github.com/open-formulieren/open-forms/issues/1127 needs to be solved first

**Comment by SilviaAmAm** [comment]
Looking at the HadM form bezwaar-gemeentelijke-belastingen. The problem here seem to be the 'selectboxes'.

If they are within a hidden component, they have a value of `undefined` which makes the summary page fail.
