### ISSUE TITLE
Adding variables to forms

### ISSUE THREAD

**Issue by SilviaAmAm** [open-formulieren/open-forms#1325]
It should be possible to define variables in the Admin form builder associated with a form:

- It should be possible to give these variables initial values when building the form. 
    - The values can have different types: numbers, strings, dates.
- The values in the variables can be used in the logic rules
- The values of the variables can be updated by the logic rules
- It should be possible to use the value of a field in the label of another field, like for example a new field could have the label 'email address of {{ surname }}'.

When the form is filled in by the user, these variables will be included in the data that is sent to the chosen registration backend.
It should also be possible to include them in a submission report (PDF) and in the confirmation email. 

**Problems with using hidden field**
- You have to choose a particular component with a specific type and then mark it as 'hidden'. 
- Each component has too many options that are not needed in the case of a variable.
- You then end up with many hidden component intertwined with visible components in the field without a clear differentiation.
- If you have many variables in a step, then you end up having a list of fields that is too long.

**Comment by joeribekker** [comment]
Ok, I understand what they want. They basically want to sent arbitrary data to the registration backend. I think it's possible.

**Comment by sergei-maertens** [comment]
Been analyzing this for a bit and came up with this initial technical specification

---

# Open Forms variables feature

Variables are an abstraction layer between the form definition and filled out values.
If implemented correctly, variables can be used in a number of places:

- Form component values
- Form component metadata (label, help text, content...)
- Calculated values from input data and/or other variables
- Logic (both reading from and writing to variables)

There is potential to leverage variables to manage client-side translations (e.g. by
attaching a language metadata element to a variable combined with the client requested
language).

## Requirements

* Define variable for every (input) component (automatically?)
* Define static variables with (initial) value
* Reference variable values as input for logic expressions
* Reference variables as target for logic actions
* Specify value output of a component to a (particular) variable
* Ability to handle collections (lists with indices) in a variable and/or collections
  of variables
* Reference and interpolate variables as part of component definitions (label, help
  text, HTML/WYSIWYG content...)
* Attach metadata to variables, such as:
    - user input vs. calculated result
    - variable origin (form component vs. explicitly defined)
    - type information (infer from component or explicitly define)
    - set/modified timestamps?
* Manage variables at the form-level in a dedicated tab
* Include form variables in imports/exports & version history
* Extract (nested) data from evaluation sources, e.g. DMN outputs a result -> point to
  a sub key

**Nice to have**

* Track variable usage/dependency tree, combined with order of components/logic rules +
  order of operations in backend (custom field types -> prefill -> input data ->
  calculated values (from logic))

## Data model

**FormVariable**

Describes the definition of a particular variable.

- allow validation that a referenced variable exists
- allow storing type metadata etc.
- allow validating the value for the value based on type information
- needs to be attached to form instead of form definition, otherwise no user-defined vars
  possible.
- what if re-use needed with form definitions?
- readonly configuration if source == component

```yaml
---

FormVariable:
    form: FK
    formDefinition: FK  # possibly not needed depending on how frontend is implemented
    name: string:slug
    source: component|userDefined
    preFillConfiguration:
        plugin: StUF-BG|HaalCentraal|KVK
        attribute: <plugin-attribute>
    type: inferedFromComponent|string|number|boolean|object|array|null
    format: inferedFromComponent|datetime|date|...
    initialValue: null|<value>
    isSensitiveData: inferedFromComponent|boolean
```

form/formDefinition: mutually exclusive & name must be unique?

TODO:

- keep in sync with form definitions, which may be re-used across forms -> extract from
  full form configuration?
- extract as part of FormDefinition.save?
- What about the JSON editor for complex values?

METHODS:

* `to_python` -> grab the type information and cast to proper python type. E.g. string
  data in ISO-8601 -> `datetime`. Especially relevant for `userDefined` variables.

**SubmissionVariableValue**

Holds the value of a particular variable in the context of a given submission.

-> Read-only variables for language management/calculated variables?

```yaml
SubmissionVariableValue:
    submission: FK
    formVariable: FK
    value: JSONField
    metadata:
        source: userInput|prefill|logic|dmn|...
        language: nl|en|de|...
        setAt: datetime
        modifiedAt: datetime
```

### Form designer

1. Extra tab to manage variables
2. Read-only variables generated from Formio components, match with existing variables
   stored in backend.
3. Display column per data source (in order): prefill, user input, logic (link to relevant logic rule(s) setting the value)
4. Variables from 3. cannot be removed, only prefill can be configured/altered
5. Add custom variables

    1. Enter name (validate uniqueness client-side)
    2. Specify type
    3. Specify data source (prefill, user input, other variable?, dotted lookup?, jq expression?) COLLECTIONS ARE CHALLENGING HERE

6. Variable state managed at top-level, e.g. modifying logic should allow option to
   "store in variable" and declare the variable from the logic tab.


### Run-time

1. Start form
2. Define all variable values that need/have an initial value (e.g. allocate the static
   variables)
3. GET SubmissionStep:

    1. Evaluate custom fields that change configuration
    2. Evaluate prefill + store in variables for prefill source
    3. Set component['defaultValue'] based on prefill variables? or emit
       SubmissionStep.data based on variables?
    4. Evaluate logic based on variables
    5. Interpolate variables in component configuration(s)

4. PUT SubmissionStep/POST logicCheck:

    1. Store all user-input data into variables
        - Keep dirty data as unsaved instances? or save after all? -> what about the
          "pause and continue later" feature?
    2. Evaluate custom fields that change configuration
    3. Evaluate prefill + store in variables for prefill source
    4. Set component['defaultValue'] based on prefill variables? or emit
       SubmissionStep.data based on variables?
    5. Evaluate logic based on variables
    6. Interpolate variables in component configuration(s)


### Logic rework

* Logic operations need explicit order
* Advanced/simple logic rules -> mix so that the order can be enforced
* Add DMN evaluation logic option (#1469)
    * configure DMN engine to use
    * select decision definition (+ version) to use
    * select which variables to input (and potentially map the variable name)
* Add logic operation to manipulate variabels, e.g. extract particular sub-key of nested
  structure (jsonLogic)

### Special points of attention

* Form export/import -> needs to include variable definitions
* Data cleaning: ensure variables values are obfuscated/deleted for sensitive data
* Data migration: create all variables + values for existing forms/submissions
* Public API: `submission.data` -> populate from variables instead of underlying JSONFields
* Check impact on formatters?
* Check impact on type-casting to proper Python types?
* Rework some BPMN Camunda integration, which already has concept of variables, sort of

**Comment by joeribekker** [comment]
> preFillConfiguration:
>        plugin: StUF-BG|HaalCentraal|KVK
>        attribute: <plugin-attribute>
> ...
>
>     initialValue: null|<value>

Prefill might be modelled as a type of initial value

> 4. PUT SubmissionStep/POST logicCheck:
> ...
> Evaluate prefill + store in variables for prefill source

This can probably be only done once: After login?

**Comment by sergei-maertens** [comment]
> Prefill might be modelled as a type of initial value

I'm not sure yet how to treat `initialValue`, especially in the future if we combine it with authentic data that cannot be altered :thinking:

**Comment by sergei-maertens** [comment]
I've amended the remarks and updated the design to flesh out the logic rework and integration of variables functionality in there a bit more.

**Comment by joeribekker** [comment]
> especially in the future if we combine it with authentic data that cannot be altered

I foresee a read-only flag (or write once, since it can be prefilled, or `system-set` vs `user-set`)

**Comment by SilviaAmAm** [comment]
This will also be relevant for DigiD machtigen when using the BSN of vertegenwoordigde and gemachtigde to retrieve data with the prefills. For eherkenning there is also the additional KVK of the company being represented. https://github.com/open-formulieren/open-forms/issues/1471

**Comment by SilviaAmAm** [comment]
# To Do 
(based on the POC https://github.com/open-formulieren/open-forms/pull/1573):

**FormVariable backend**

- [ ] `FormVariable` model: 
	- [ ] Implement the `get_initial_value()` method for the different possible variables.
- [ ] `FormVariableAdmin`
- [ ] `FormVariableSerializer` (List serializer) that can handle the bulk create and bulk update
- [ ] `FormVariablesViewset`: does bulk updates / creates / deletes / list of `FormVariable` 


**FormVariable frontend**

- [ ] New tab in the form builder for the variables. 
	- [ ] Retrieves existing variables if it is an existing form or automatically adds the static variables
	- [ ] Whenever a component is added / deleted / changed the variables are updated in the react state
	- [ ] When the form is saved they are POSTed in bulk to the `FormVariableViewset`
- [ ] Make the variables selectable in the logic rules
- [ ] Add support for adding custom variables


**SubmissionVariableValue backend**

- [ ] `SubmissionVariableValue` model
- [ ] Admin
- [ ] `SubmissionVariableValuesState` dataclass with `get_variables_to_prefill` and `get_data` methods
- [ ] Update `Submission` model to have the load_submission_variable_values_state which saves on the instance the unsaved `SubmissionVariableValue`s
- [ ] Update `get_dynamic_configuration` so that it injects the variables in the configuration. This includes values, labels (eg using `{{ variable }}` in the label of a component) and html in case of the content component.
- [ ] Prefill: update `SubmissionViewset` so that in the perform create, the `SubmissionVariables` are prefilled
- [ ] Update `SubmissionStepViewSet` so that on PUT to update the `SubmissionVariableValues` are updated

**Other**
- [ ] Documentation

**Still to figure out**
- Include variables in submission report + confirmation email
- Include variables in the data sent to the registration backend

**Comment by joeribekker** [comment]
Nice work!

Regarding the figuring out thing:
1. We can just make all variables available as template variable, and only include formfield-variables as summary (basically what we have now). This allows you to include the other variables (like tax calculations, or reimbursements) in any way you like.
2.  I think we should remove the registration tab, where you can select a ZGW/StUF-attribute, from the components and move this to a new tab "registration mapping" (or put it in the existing registration tab). What this mapping shows is a table with the first column all variables (read only) and the 2nd column a ZGW/StUF attributen you can map it to.

Regarding the 2nd bullet. I might also see this for prefilling. Rather then stuffing this feature in the variables tab. This makes variables by itself simpler perhaps as well since we can model it in a different model.

**Comment by SilviaAmAm** [comment]
Current issues to deal with in FormVariable part:

- [ ] If there is a component with key 'var1' in a step, and a new component 'var1' is added to another step, the second one doesn't get linked to a new variable
- [ ] If a user adds a user defined FormVariable with key 'var1' and there is a component with key 'var1' in a step, then the backend will raise an error because there are duplicate keys.

**Comment by SilviaAmAm** [comment]
The bulk of this issue is now implemented. The remaining work is split into new issues:
1. Documentation: https://github.com/open-formulieren/open-forms/issues/1705
2. Camunda variables refactor: https://github.com/open-formulieren/open-forms/issues/1706
3. Data migration to migrate old forms that didn't use variables: https://github.com/open-formulieren/open-forms/issues/1707
4. Create an interface to fill different properties (label, html, ...) of components in the Formio configuration: https://github.com/open-formulieren/open-forms/issues/1708
5. Deal with conflicting keys: https://github.com/open-formulieren/open-forms/issues/1697
6. Include variables in submission reports / emails / registration backends: https://github.com/open-formulieren/open-forms/issues/1709
7. Implement repeating components by making use of the variables: https://github.com/open-formulieren/open-forms/issues/1710
