### ISSUE TITLE
Mark steps as n/a via logic causes issues when navigating back

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#1350]
Create 2 steps, create logic to mark 2nd step as n/a. Fill in form, make sure 2nd step is marked as n/a and go to overview page. Navigate back (should bring you to step 1 since step 2 is n/a) and the next-button remains gray.

**Comment by sergei-maertens** [comment]
The fix for #1274 took care of this issue as well - a logic check is now scheduled after the form step is loaded, causing the button to be enabled if continuing is allowed.

This _is_ a side-effect of the logic check and working as intended now, however this might be relevant again in the future if we manage to do some small optimizations (since the data was just loaded from the endpoint which does the logic check as well, we don't need to do an explicit check on load, but factoring this out is not straight-forward at the moment).
