### ISSUE TITLE
Deselecteren van radio button breekt logic zichtbaarheid toggle

### ISSUE THREAD

**Issue by Bartvaderkin** [open-formulieren/open-forms#1526]
### Product versie / Product version

Production & development

### Omschrijf het probleem / Describe the bug

Ik heb een formulier met een radio group met twee opties, met daaronder twee verborgen radio groups. In de formulier logica zijn twee regels waarmee afhankelijk van de keuze voor de eerste radio button 1 van de twee onderste radio groups zichtbaar EN verplicht wordt gemaakt (en de ander verdwijnt).

Het gaat mis dat als je in de onderste groepen eerst een optie kiest en die dan weer deselecteerd, dan breekt er iets zodat je in de bovenste group niet meer de andere optie kan aanklikken. 

Mogelijk gerelateerd is dat de `clearOnHide` niet werkt zoals ik verwachte: eg bij heen en weer klikken tussen de bovenste opties en waarbij dus de onderste tonen/verbergen houden die hun selectie vast.

via DH Taiga 30

### Stappen om te reproduceren / Steps to reproduce

Zie omschrijving of https://open-forms.test.maykin.opengem.nl/issue-logic-visibility-toggle/

- Kies ‘Opties 1’, dan komt er een radio blok onder
- Selecteer daarin ‘Opties 1 Ja’, en de-selecteer diezelfde optie (zodat er onderin niks geslecteerd is).  
- Kies dan bovenin ‘Opties 2’ maar dan blijft het onderste blok hangen (en er verschijnen niet ‘Opties 2 Ja/Nee’). 

Het lijkt dat het misgaat mis op het deselecteren/verplicht.

### Verwacht gedrag / Expected behavior

Ik verwacht dat de widgets niet vastlopen door gebruikers interactie (en zie omschrijving/repro).

### Screen resolution

1920 x 1080

### Browser

Desktop

### OS

Linux

### Browser

Firefox

**Comment by Bartvaderkin** [comment]
Also note I also tested this with @sergei-maertens https://github.com/open-formulieren/open-forms-sdk/pull/190 and current development backend but the problem happens the same.

**Comment by sergei-maertens** [comment]
I can at least explain the current behaviour - 

1. The form is empty, no data, so it's considered 'valid'
2. Select in the first radio options -> form is valid -> backend logic check is executed
3. Select in the second radio -> form is valid -> backend logic check is executed
4. De-select option in the second radio -> field is required, with no value selected -> form is NOT valid -> backend logic check is not executed (because it requires client-side validation to pass first)
5. Change option in first radio -> second radio is still invalid -> backend logic check is still not executed

Possible workaround is (detecting the order of the changed data and) firing backend logic checks even if the form is invalid.

**Comment by sergei-maertens** [comment]
I've opted to always call the backend but strip out the invalid data.
