### ISSUE TITLE
Postalcode field cannot work with postal prefill

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#1693]
### Product versie / Product version

1.1.2

### Omschrijf het probleem / Describe the bug

Prefilling returns a postal code in the form "1000AA" (without space). The postalcode validates the form "1000 AA" (with space). The postal code without a space is forced into the value of the postalcode field, rendering it correctly but fails the validation (for some reason).

### Verwacht gedrag / Expected behavior

We should decide on 1 format or relax the behaviour.

**Comment by sergei-maertens** [comment]
So it *seems* that the correct format for postal codes is `1000 AA` (with the space), however the prefill plugin backends do not guarantee that this space is included or not included. Picking one format is therefore not an option, since a plugin can always return _the other_ format.

Since prefill results in a formio `defaultValue`, I'm setting this up as a normalization step that can run in the context of the specific component. Specifically for the postcode component, we can apply the same mask logic from formio and re-format whatever input we get from the prefill plugin.
