### ISSUE TITLE
Unique keys

### ISSUE THREAD

**Issue by SilviaAmAm** [open-formulieren/open-forms#1697]
### Product versie / Product version

latest

### Omschrijf het probleem / Describe the bug

1. If I create a component with key 'var1' in step1 and a component with key 'var1' in step 2, the second component is not linked to a variable (because of the keys conflict)
2. If I add a user defined variable and then a component with the same key, I have two variables with duplicate keys (this will raise an error in the backend but it is not yet shown in the frontend).

### Verwacht gedrag / Expected behavior

1. Unique variables should be created for both components
2. There should be a warning when creating the component that this key is already in use?

**Note**
We should first discuss namespacing before tackling this issue!

**Comment by sergei-maertens** [comment]
Discussed - when a duplicate key arises because of a component being added, we allow adding the component with this key, but instead display a validation error with the (user-defined) variable explaining that the key is duplicated "now" by a component.

The idea is that the form designer then update their user-defined variables and related logic rules.
