### ISSUE TITLE
Hidden fields with default value present in data

### ISSUE THREAD

**Issue by SilviaAmAm** [open-formulieren/open-forms#1755]
### Product versie / Product version

1.1, latest, probably also 1.0

### Omschrijf het probleem / Describe the bug

Hidden fields with a default value that are made visible by logic and then hidden again are not removed from the data.

**Note**
This is also a problem with the variables

### Stappen om te reproduceren / Steps to reproduce

In the admin
1. Create a new form
2. Add a checkbox 
3. Add a text field with hidden checked and 'Test data' as default value
4. Add an advanced logic rule with trigger `{"==":[{"var": "checkbox"}, true]}` and action `change a property `of the `textField`, property `hidden` value `false`.
5. Save the form

In the SDK:
1. Check the box
2. Uncheck the box
3. Submit the form

In the Admin, check the submission. The data contains the field `textField: 'test data'`

### Verwacht gedrag / Expected behavior

The hidden field should be removed from the data

Relates to #1527  and the patch for that (#1528)

**Comment by sergei-maertens** [comment]
I can reproduce this with the exact steps described.

I think the following is going wrong:

1. We merge all the data together, grabbing the defaults from components: https://github.com/open-formulieren/open-forms/blob/master/src/openforms/submissions/form_logic.py#L74
2. The default value from components does not consider whether the component is hidden/`clearOnHide` is set (!)
3. Because it's a default value and not explicit input-data, it seems to end up in the data diff: https://github.com/open-formulieren/open-forms/blob/master/src/openforms/submissions/form_logic.py#L164 (? unsure about this, as we seem to use `step.data` only?)
4. The data reset seems to be failing/not executing because the value is grabbed from the defaults rather than just set to an empty value: https://github.com/open-formulieren/open-forms/blob/master/src/openforms/submissions/form_logic.py#L175
5. The resulting default value is returned from the logic check endpoint, where it's picked up by the SDK, which sets the value as an "explicit input" -> formio is no longer in "default value" behaviour and like that it ends up in the submission data

I think that in step 4 we should delete the key from `data_diff` rather than setting it to the default/empty string and then Formio's normal behaviour (`clearOnHide`) should kick in?

Either way - this should be sufficient information to further diagnose and solve the bug.

**Comment by sergei-maertens** [comment]
I've reproduced the steps on 1.0.13 and this is still happening on current master (e3df78f87b4d7665d4e297dda1d375f41a56ee08)

**Comment by joeribekker** [comment]
I don't think we should backport this because users might rely on this now (although I doubt it).
