### ISSUE TITLE
Pressing "pause"/"tussentijds opslaan" sends an email with an incorrect greeting

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#1787]
### Product versie / Product version

1.1.3

### Omschrijf het probleem / Describe the bug

This message should be made configurable, like the other email templates. Please make it configurable on generic config (no need to do it per form).

![image](https://user-images.githubusercontent.com/96970/178987426-bba2041d-0fa6-4a84-b132-13c01c8fca5b.png)

**Comment by sergei-maertens** [comment]
**Acceptance criteria**

- [ ] Global configuration option in the admin page where admins can enter a template
- [ ] Current template is used as default value for the configuration option
- [ ] E-mail uses the template from config option rather than from file
- [ ] Plain text version of e-mail (still) works
- [ ] Template is syntax validated like other template configuration options
- [ ] Documentation (on RTD) is updated with available context variables
- [ ] Tests added and passing
    - [ ] Test that the config can be added via the admin
    - [ ] Test that the input is validated for valid syntax/allowed template tags etc.
