### ISSUE TITLE
Strange behavior address filling

### ISSUE THREAD

**Issue by sjoerdie** [open-formulieren/open-forms#1832]
### Product versie / Product version

1.0.12

### Omschrijf het probleem / Describe the bug

Venray-test form: Aanmelding (water)verblijfsbelasting. 

When you fill in the form and choose "nee, ik heb een ander postadres" and fill in the other address fields all the fields start flashing as if its in a sort of loop constantly prefilling the address fields. 

I tried to record it, but all of the sudden the strange behavior was gone. 
Silvia did witness it when I showed her. 

### Stappen om te reproduceren / Steps to reproduce

1. Go to the form aanmelding-waterverblijfsbelasting for Venray-test
2. Fill in the first block
3. Choose 'nee, ik heb een ander postadres'
4. Fill in the fields again
5. All the fields (also from the previous block) are emptied and filled again, this goes on for minutes, but stops after a while;

### Verwacht gedrag / Expected behavior

Fields should just be filled. 

### Screen resolution

bigger

### Device

Desktop

### OS

Linux

### Browser

Chrome

**Comment by joeribekker** [comment]
Could not be reproduced, moved to backlog until it re-appears.

**Comment by sjoerdie** [comment]
Our Venray stakeholder called, she created a new form and had the issue again, she recorded it with her smartphone:

https://user-images.githubusercontent.com/85243022/185163386-d3995224-edd1-47e8-9359-7a4c52b3bb32.mp4

I tried the same form from my workstation and also experienced the flickering, although not as long as in the movie. 

![image](https://user-images.githubusercontent.com/85243022/185164289-1881ceb7-d45a-4bcc-af41-a6d2c407e9ef.png)

This goes on for about 2 pages. 

So can be reproduced, please give it some attention.

**Comment by joeribekker** [comment]
Okay, this seems to happen quite often in 1.1.5 (but I cannot reproduce it).

I think it's the logic eval and the autocomplete API-calls competing with eachother or something. Should we make this autocomplete behaviour not part of the logic check @sergei-maertens ?

**Comment by sergei-maertens** [comment]
I will work on this tomorrow. I think Joeri is right with his suspicions and I think I agree with the suggested solution.

**Comment by sergei-maertens** [comment]
I can indeed reproduce this on the test environment (which is on version 1.1.5). In master, we had #1717 which messed around a bit in this code and should not trigger all these API calls. I'll see if I can confirm this.

**Comment by sergei-maertens** [comment]
I'm fairly certain I've figured out what's happening now.

1. While testing locally with a mock-client for location autocomplete (using hardcoded data), I could *not* reproduce this at all
2. I found the code path that clears the field value if the get-street-name-and-city endpoint returns an empty object [here](https://github.com/open-formulieren/open-forms-sdk/blob/7a61b636a47c4d0e973f4ce2437791b717709a3a/src/formio/components/TextField.js#L36). This explains the flicker _if_ at some point one of the requests returns an empty response -> field is being cleared, and then filled again by another request.
3. The screenshot of the requests is clear - there are requests fired for _every keystroke_ in the form, provided the postal code + number are filled out. Even if you're modifying a "name" field completely unrelated to these address fields (because this logic is hooked into the fieldlogic method)

Looking at the BAG client implementation, I see that we catch any unexpected exception, log it, and then return an empty dict, leading to an empty response.

* I could not find anything in Sentry, not for this testenv, not for any other environment
* I could not find log records in the container logs - which is strange in itself considering it's a `logger.exception` call -> to investigate separately.
* We also have a code path that returns empty dict if `_embedded` is not found in the response -> this may very well be the culprit!
* In APM I was able to find a transaction that failed (the API call to the BAG API, acceptance environment) - with a HTTP 429 -> we are being throttled!

Conclusion:

* our API calls fire too often
* our API endpoint does not have caching, but instead just passes it downstream to the BAG client
* the BAG API (very reasonably) returns either empty responses or downright rate limits us (again, very reasonable)
* this results in an empty response being received by the SDK
* which in turn reacts by clearing the field
* another un-throttled request goes through and returns actual data -> the data is set again

Mitigations I shall apply in the patch:

* SDK: only make the API calls if there is no value set in the field (or it is read-only, matching the logic of #1717)
* backend: apply caching layer so we don't hit the BAG downstream API for results we already have

I still think that this should indeed be handled through our dynamic config/logic module rather than having the component making API calls, but that's a bigger refactor than I'd like which presents problems with backporting as well. So, for now, I'd prefer applying a bandaid fix.

**Comment by joeribekker** [comment]
agreed with your bandaid.
