### ISSUE TITLE
Updating the form configuration while user fills out form results in data not being saved

### ISSUE THREAD

**Issue by SilviaAmAm** [open-formulieren/open-forms#1928]
### Product versie / Product version

latest

### Omschrijf het probleem / Describe the bug

The current behaviour is that if a user is filling out the form, but the definition is updated, then the data is not saved. 

It happens because no form variables are retrieved from this query:
https://github.com/open-formulieren/open-forms/blob/master/src/openforms/submissions/models/submission_value_variable.py#L100

(the saved_submission_value_variables.values_list( "form_variable__id", flat=True) contains a list with None).

Taken from this discussion: https://github.com/open-formulieren/open-forms/pull/1893#discussion_r952424440

**Comment by SilviaAmAm** [comment]
The query:
```python
form_variables = FormVariable.objects.filter(
    ~Q(
        id__in=saved_submission_value_variables.values_list(
            "form_variable__id", flat=True
        )
    ),
    form=submission.form,
).select_related("form_definition")
```

 doesnt return any variable if: 
```python
saved_submission_value_variables.values_list(
    "form_variable__id", flat=True
)
```
contains any `None` values. Maybe it could be changed to something like:
```python
Q(
    key__in=saved_submission_value_variables.values_list(
        "key", flat=True
    )
)
```

But there is also the fact that when we retrieve the data for a form step, we call this (with `include_unsaved=False`):
```python
    def get_variables_in_submission_step(
        self,
        submission_step: "SubmissionStep",
        include_unsaved=True,
    ) -> Dict[str, "SubmissionValueVariable"]:
        form_definition = submission_step.form_step.form_definition

        variables = self.variables
        if not include_unsaved:
            variables = self.saved_variables

        return {
            variable_key: variable
            for variable_key, variable in variables.items()
            if variable.form_variable
            and variable.form_variable.form_definition == form_definition
        }
```
Here any saved submission value variable (from before updating the configuration) is not returned because it has `variable.form_variable=None`.

**Comment by sergei-maertens** [comment]
For transparency after putting this on Slack, also here on Github:

**About recoupling**

> We could try to recouple the submission value variables with form_variable=None to the new FormVariables that have been created in the configuration update.

I think we should do this, whether it's a good idea or not. If the key is the same, we keep the current behaviour (JSONField data works based on key from formio config, if they change a field type pre 2.0 and re-use a key, you may still end up with a type mismatch with data that's in the submission). The benefit of this is that we track relations which may aid debugging.

To properly and fully resolve this, we would have to store a frozen (complete) formio configuration definition (all steps) with the submission model and use that as a "historic" form definition (and this is a different ticket alltogether).

In terms of implementation, I think I'd fire a celery task from the FormVariable bulk endpoint update to go over all the submissions and fix the `SubmissionValueVariable` references to `FormVariable`. That way, we don't hold up the main request-response cycle.

**Proper solution**

As for the actual solution - we could only keep the form_variable reference as "interesting metadata" and do all the queries based on key rather than trying to link it through form_variable. this would mean grabbing all the keys from the form step configuration & using that as (query) filter. 

In the end this may be the most robust solution, so we're only taking (submission value) variables that are explicitly in the form, by key.
