### ISSUE TITLE
Better tools to work on or update an existing form

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#1967]
### Thema / Theme

Frontend

### Omschrijving / Description

When a Form is **not active** or in maintanance, it should:

* [x] All users with an active session should not be allowed to continue, ie they should get a message when continueing the form is no longer available.

When a form is in **maintanance**, it should:

* [x] Still allow admin users to use the form
* [x] Regular users should get a message when the go the next step, or submit the form, and thus cannot complete the form.

Ergo, active is for everyone. Maintainance is for regular users.

**Comment by sergei-maertens** [comment]
If you have an ongoing submission, should the submission be removed from the session? I think so:

* Otherwise refreshes will still load the submission, removing it will lead to HTTP 403 on refresh.
* Any subsequent actions fall in the 403, so even if we miss some endpoints, we have a robust fallback mechanism
* The SDK stores a mapping of form ID/slug to submission ID for hard refreshes so that you can resume the form where you left of. Removing it from the session automatically causes the localstorage to error and clean up on reloads.

You can make a case for deactivated vs maintenance mode, only clear the session in the former, as it is not expected to change back, while maintenance mode is temporarily disabling the form and the user could resume it later on (technically).

This also makes me think that deactivated forms should probably also trigger the hashing/cleanup of submission objects, as this hook will not run naturally, and that makes me wonder what happens with submissions that are aborted halfway through.
