### ISSUE TITLE
Een element waarbij enkel een postcode ingevuld kan worden. Voor de Nederlandse postcodes vindt een validatie ...

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#209]
...plaats. Buitenlandse postcodes zijn ook in te vullen.

Eis: Elementen 1u.
Zie ook NvI: 71, 144

**Comment by joeribekker** [comment]
@shea-maykinmedia I think you tackled this already?

**Comment by shea-maykinmedia** [comment]
@joeribekker The Dutch postcodes and validation was done here https://github.com/open-formulieren/open-forms/pull/461 however the way it's implemented it only accepts Dutch postcodes and not foreign post codes.  

For foreign post codes I'm not sure if we want a separate component or to just use the Text Field Component since for foreign post codes I think we would just want a text field where anything can be entered.

**Comment by joeribekker** [comment]
Agree
