### ISSUE TITLE
Align columns 

### ISSUE THREAD

**Issue by SilviaAmAm** [open-formulieren/open-forms#2113]
### Thema / Theme

Frontend

### Omschrijving / Description

Den Haag Taiga user story 280, issue 274

The columns alignment doesn't look right:
![kolom uitlijning](https://user-images.githubusercontent.com/19154114/194035139-71bae3d2-bd06-48f8-9bf1-ee14973b398c.png)

This happens also in the form editor:
![kolom uitlijning in de editor](https://user-images.githubusercontent.com/19154114/194034937-68affb49-cae8-41c6-92f8-c962656e43b7.png)

**Comment by sergei-maertens** [comment]
Discussed through a call - these complex layouts were not anticipated and also don't seem possible to implement without introducing a lot of breaking changes (and they will cost a lot of time and effort!).

You can work around this by making multiple component rows and being creative with WYSIWYG components to mimick descriptions.

The main problem is that we can't just push down the input boxes to align them, since descriptions (and error messages) are displayed _below_ them and not guaranteed to always be present.

We will however tackle mobile styling.
