### ISSUE TITLE
Als dienstverlener wil ik mijn formulieren in meerdere talen kunnen aanbieden

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#2170]
Als dienstverlener wil ik mijn formulieren in meerdere talen kunnen aanbieden, zodat ik de volledige bevolking van mijn gemeente kan ondersteunen  Oorsprong: https://github.com/Dimpact-Samenwerking/Open-Formulieren/issues/57 RTM: 9.3 Story points: 40 Business value: 5

**Comment by sergei-maertens** [comment]
**Technical analysis & implementation guidelines**

## To refine

* translations on/off per form -> can we still look at the browser locale preference? If not, what should be the language then, NL?
* changing language forces restart of the form: why is this needed? System values/keys should be language-agnostic - only user-presented labels etc. are translated (e.g. dropdown values stay the same, but the options are translated)

## Foundational work

Preparation work so that the runtime-language can be set/specified by the end-user and eventually have the translations be activated in the correct language.

### Backend preparation

- [x] Define supported languages in `settings.LANGUAGES` (currently set to `en` and `nl`, which is ok. Later on we can add more languages).
- [ ] Enable `LocaleMiddleware` - django middleware to detect preferred language from `Accept-Language` request header and/or language cookie
- [ ] Configure language cookie similar to session cookie (`LANGUAGE_COOKIE_` prefix) (httpOnly, secure, samesite)

### i18n API endpoints

- [ ]  Add `GET /api/v1/i18n/info` endpoint, return data:
  ```json
  {
    "languages": [
      {
        "code": "en",
        "name": "English"
      },
      {
        "code": "nl",
        "name": "Nederlands"
      }
    ],
    "current": "nl"
  }
  ```
  * exposes the available languages
  * exposes which language the user has selected (this is based on the `LocaleMiddleware`)
  * in-browser language detection via javascript is unreliable, best to have the backend expose this
  * Take an optional `?hint=` querystring param, which will contain the value from the `html.lang` attribute - use this is fallback (browser preference should always override this if possible).

- [ ] Add `PUT /api/v1/i18n/language` endpoint to set the language, request body `{"code": "nl"}`. This needs to result in the language cookie being set, so check Django's i18n tools for that

### SDK modifications

- [ ] Implement language selection/dropdown component
  * Populate options and current value from `/api/v1/i18n/info` - send the `lang` attribute value from the document as `hint` query param
  * On change, set the client-side language AND make a `PUT` call to `/api/v1/i18n/language`
- [ ] Add an SDK init option `languageSelector` with a DOM node reference or string to pass to `document.querySelector(...)`.
- [ ] IF the form enables translations, render the language dropdown in `languageSelector` (using React portal!). If `languageSelector` is empty-ish (empty string, `null`, `undefined`...), render it before the `App` component in `open-forms-sdk/src/sdk.js`)
- [ ] Ensure the selected language/locale is passed down to the formio options.
  TODO: define and implement behaviour when the language is changed (full reload or not? see the "to refine" section above)

### Create static translations

:warning: Mostly external party that will manage the translation assets, we need to provide the right tooling though

- [ ] Expose rosetta to translators for NL/EN translations
- [ ] Distribute SDK `i18n` catalogs (initially)
- [ ] (later) set up infra to manage SDK translations
- [ ] (later?) set up CI pipeline to prevent broken translations breaking the build

## Translating content

...

**Comment by PaskalKiers** [comment]
Testopmerking vanuit projects. Zou niet geregistreerd moeten worden. Anders Sorry :(
