### ISSUE TITLE
(SDK) Implement language selection component

### ISSUE THREAD

**Issue by sergei-maertens** [open-formulieren/open-forms#2253]
Epic #2170

The SDK needs to provide a component displaying the available languages and making it possible to change the desired language.

- [x] Add `LanguageSelection` React component
    - [x] Build this on top of the Utrecht CSS component/design, see https://nl-design-system.github.io/utrecht/storybook/?path=/docs/css-alternate-lang-nav--default-story
    - [x] Add the component to storybook
    - [x] The available language data & state needs to be derived from the API endpoint (see #2229)
    - [x] When the language is changed, ensure this is persisted with a PUT call (see #2229)
- [x] #2303
- [x] Add an (optional) SDK option with a DOM node or selector string for where to mount the language selection
    - If not provided, add a div above the main form content to render it (spanning the form + progress indicator)
    - if provided, render in the referenced node using a [portal](https://reactjs.org/docs/portals.html)

**Comment by Robbert** [comment]
I improved the language switcher code a bit, and made a separate version for client side switching that uses toggle buttons instead of links:

- [CSS Component that uses links](https://nl-design-system.github.io/utrecht/storybook/?path=/docs/css-alternate-lang-nav--default-story) - now uses `nav` and `aria-labelledby` to reference a hidden heading.
- [CSS Component that uses a button group](https://nl-design-system.github.io/utrecht/storybook/?path=/docs/css-alternate-lang-nav--button-group): uses a `region` landmark (through a `<section>` element) to make it more easily discoverable using Voice Over for example
- [React code example for language switcher with a button group](https://nl-design-system.github.io/utrecht/storybook-react/index.html?path=/docs/react-alternate-lang-button-group--default): The code snippet rendering in Storybook is currently a bit of a mess for this story, but combined with the CSS component you'll get the idea.
