### ISSUE TITLE
Ogone on Failure/Cancel: Method (POST) not allowed

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#2362]
### Product versie / Product version

2.0.0

### Omschrijf het probleem / Describe the bug

internal ref: Rid 83
sentry: 318987

When a payment is cancelled or failed Ogone prompts the user to Cancel or go back:
![image](https://user-images.githubusercontent.com/112621537/202404853-518710f8-eabd-4ea3-8866-5372af803065.png)
When the user selects Back, a POST request is made to Open Forms:
![image](https://user-images.githubusercontent.com/112621537/202402741-513ae9d5-21f7-47a3-a47b-6f734f8bc236.png)
which is not allowed:

``` json
{
    "type": "https://formulieren-xxxxxxxxx.nl/fouten/MethodNotAllowed/",
    "code": "method_not_allowed",
    "title": "Methode \"{method}\" niet toegestaan.",
    "status": 405,
    "detail": "Methode \"POST\" niet toegestaan.",
    "instance": "urn:uuid:dd1ce704-e86f-xxxx-xxxx-af9f8e3d740f"
}
```

This exception is raised because plugin.return_method is set to "GET".

**Comment by sergei-maertens** [comment]
Implementation/bugfix notes:

- [ ] POST must be allowed for return from Ogone
- [ ] endpoint must be CSRF exempt since Ogone cannot obtain and send a CSRF token
- [ ] we must validate that the request really originates from Ogone, so that will probably require validation of some sort of token/hash with our SHA-IN and/or SHA-OUT

**Comment by joeribekker** [comment]
I'm removing the milestone since we think this was caused by a misconfiguration. If this seems to happen with more users then we can re-evaluate.

**Comment by sergei-maertens** [comment]
I can reproduce this with our own Ogone account, but it seems like the `METHOD NOT ALLOWED` error is actually masking another error:

```
2023-03-10 12:28:31,730 DEBUG openforms.setup  Session is already patched OR has an ``_original_request`` attribute.
2023-03-10 12:29:03,258 ERROR openforms.api.exception_handling  Exception be5fd7ee-bc0f-4c21-a1b7-894ab0cd93bc ocurred
Traceback (most recent call last):
  File "/home/bbt/.virtualenvs/open-forms/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/bbt/code/open-forms/src/openforms/payments/views.py", line 248, in post
    return self._handle_return(request, *args, **kwargs)
  File "/home/bbt/code/open-forms/src/openforms/payments/views.py", line 218, in _handle_return
    raise MethodNotAllowed(request.method)
rest_framework.exceptions.MethodNotAllowed: Method "POST" not allowed.
2023-03-10 12:29:03,273 ERROR django.request  Internal Server Error: /payment/04a838ff-e5af-4fc1-8321-0cd12c51be97/return
Traceback (most recent call last):
  File "/home/bbt/.virtualenvs/open-forms/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/bbt/.virtualenvs/open-forms/lib/python3.10/site-packages/django/core/handlers/base.py", line 204, in _get_response
    response = response.render()
  File "/home/bbt/.virtualenvs/open-forms/lib/python3.10/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/bbt/.virtualenvs/open-forms/lib/python3.10/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/home/bbt/.virtualenvs/open-forms/lib/python3.10/site-packages/djangorestframework_camel_case/render.py", line 18, in render
    return super(CamelCaseBrowsableAPIRenderer, self).render(
  File "/home/bbt/.virtualenvs/open-forms/lib/python3.10/site-packages/rest_framework/renderers.py", line 724, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
  File "/home/bbt/.virtualenvs/open-forms/lib/python3.10/site-packages/rest_framework/renderers.py", line 696, in get_context
    'post_form': self.get_rendered_html_form(data, view, 'POST', request),
  File "/home/bbt/.virtualenvs/open-forms/lib/python3.10/site-packages/rest_framework/renderers.py", line 501, in get_rendered_html_form
    serializer = view.get_serializer(**kwargs)
  File "/home/bbt/.virtualenvs/open-forms/lib/python3.10/site-packages/rest_framework/generics.py", line 108, in get_serializer
    serializer_class = self.get_serializer_class()
  File "/home/bbt/.virtualenvs/open-forms/lib/python3.10/site-packages/rest_framework/generics.py", line 122, in get_serializer_class
    assert self.serializer_class is not None, (
AssertionError: 'PaymentReturnView' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.
2023-03-10 12:29:03,276 ERROR django.server  "POST /payment/04a838ff-e5af-4fc1-8321-0cd12c51be97/return?action=cancel HTTP/1.1" 500 2852
```

at least I can reproduce this so that's something to go on.

**Comment by sergei-maertens** [comment]
Okay, a summary of all the findings so far:

1. the `GET` / `POST` configuration parameters in Ogone are irrelevant here - they only concern the webhook communication and that seems to work as intended.
2. This is about the redirect flow when returning from Ogone to Open Forms, relevant documentation is https://support.legacy.worldline-solutions.com/integration-solutions/integrations/hosted-payment-page?com.dotmarketing.htmlpage.language=1&skiprules=true&com.dotmarketing.htmlpage.language=1&skiprules=true#eCommerce-get-transaction-feedback, especially the aspect about "Redirection in the browser"
3. On success, this matches up and we are indeed redirected to a GET request. We can validate all the parameters etc. to ensure there's no tampering with the request.
4. However, when you use the iDeal cancel flow (cancel ideal and then hit "Terug" on the next screen), the documentation is not accurate - Open Forms receives a POST request. I suspect that Ogone is triggering a POST to the return URL from their own page, somehow. See browser network logs screenshot:
   ![image](https://user-images.githubusercontent.com/5518550/224309570-af8c7f5e-4357-4b5f-b38e-b54a67e2c942.png)
5. Okay, so let's accept POSt too then, right? Well, it's not as simple as that - we get a query param with the `action=cancel`, but we have no way of validating that this is a legitimate request from Ogone - there is no signature that lines up with our calcuations based on SHA-OUT, and more importantly, there's no documentation to be found about any of the parameters in the POST data. The payload for this test is:
   ```
   CSRFKEY: 0A279E1D57D3605ED17AFDD7C3292C7AFA4B3B8F
   CSRFTS: 20230310125323
   CSRFSP: /ncol/test/order_ANetb_flowhandler_UTF8.asp
   branding: OGONE
   payid: 3262534937
   hash_param: 66A731BF4497FD5C79DDD359792A9387375B8FA7
   LimitClientScriptUsage: False
   paymethod: iDeal
   reselect: Terug
   WIN3DS: 
   PMListType: 
   walletid: 
   walletalias: 
   wallethash: 
   CatalogURL: 
   HomeURL: 
   DEVICE: 
   TBLBGCOLOR: 
   TBLTXTCOLOR: 
   TPBTNBGCOLOR: 
   FONTTYPE: 
   BUTTONBGCOLOR: 
   BUTTONTXTCOLOR: 
   ```

   This implies that we cannot verify the cancellation is legitimate, so just allowing GET is not viable.

Note that in local development, you need to edit `src/openforms/conf/dev.py` and comment out this:

```py
# DRF - browsable API
REST_FRAMEWORK["DEFAULT_RENDERER_CLASSES"] += [
    "djangorestframework_camel_case.render.CamelCaseBrowsableAPIRenderer"
]
```
otherwise you get unrelated errors.

**Comment by sergei-maertens** [comment]
So, where the POST is coming from is pretty straightforward: the Ogone page has the following markup:

```html
<form class="normal" action="http://localhost:8000/payment/04a838ff-e5af-4fc1-8321-0cd12c51be97/return?action=cancel" method="POST" id="form1" name="form1" style="margin-bottom:0px;">
    <input type="hidden" name="CSRFKEY" value="135E11D3B44783A1829D9AECD40234CF695D7D40">
<input type="hidden" name="CSRFTS" value="20230310125803">
<input type="hidden" name="CSRFSP" value="/ncol/test/order_ANetb_flowhandler_UTF8.asp">
    <input type="hidden" name="WIN3DS" value="">
    <input type="hidden" name="PMListType" value="">
    <input type="hidden" name="branding" value="OGONE">
    <input type="hidden" name="payid" value="3262534937">
    <input type="hidden" name="hash_param" value="66A731BF4497FD5C79DDD359792A9387375B8FA7">
    <input type="hidden" name="walletid" value="">
    <input type="hidden" name="walletalias" value="">
    <input type="hidden" name="wallethash" value="">
    <input type="hidden" name="CatalogURL" value="">
    <input type="hidden" name="HomeURL" value="">
    <input type="hidden" name="LimitClientScriptUsage" value="False">

    <input type="hidden" name="DEVICE" value="">
    <input type="hidden" name="TBLBGCOLOR" value="">
    <input type="hidden" name="TBLTXTCOLOR" value="">
    <input type="hidden" name="TPBTNBGCOLOR" value="">
    <input type="hidden" name="FONTTYPE" value="">
    <input type="hidden" name="BUTTONBGCOLOR" value="">
    <input type="hidden" name="BUTTONTXTCOLOR" value="">
    
        <input type="hidden" name="paymethod" value="iDeal">
    
    <small><input class="ncol" type="submit" name="reselect" value="Terug" id="btn_Back"></small>
</form>
```
and clicking the "Terug" button submits this form. I've still got a nagging feeling that this should submit to Ogone itself and not our return URL, and *then* perform a proper redirect with the signing parameters.

**Comment by sergei-maertens** [comment]
I submitted a technical support ticket with WorldLine, case reference is 02945205

**Comment by sergei-maertens** [comment]
I've heard back from WorldLine and the relevant part of the response is:

> De test simulator die u gebruikt is ontworpen om te testen. Dit weerspiegeld niet 100% de productie omgeving. Wanneer u dezelfde stappen uitvoerd in de productie omgeving zal dit niet gebeuren.

> Dit is hoe de simulator is ontwikkeld en dit zal niet aangepast worden.

Summarized - this supposedly only happens with the simulator and won't be fixed. It should not be a problem in production.
