### ISSUE TITLE
Filling in and removing a frontend rule causes 500

### ISSUE THREAD

**Issue by SilviaAmAm** [open-formulieren/open-forms#2385]
### Product versie / Product version

1.1.x, 2.0.x

### Omschrijf het probleem / Describe the bug

When adding a new component to a form, the `conditional` part in the component JSON is:
```
"conditional": {
    "show": null,
    "when": null,
    "eq": ""
  },
```
If one fills in the field "The component should render" and then deletes the selected value:
![conditional](https://user-images.githubusercontent.com/19154114/203537493-fcb17c16-1b1c-44f4-aeb0-697f61a46948.png)

The json is changed to:
```
"conditional": {
    "show": "",
    "when": null,
    "eq": ""
  },
```
This causes the function `is_visible_in_frontend` to error, because it then tries to find a component with key `None` in the configuration.

Note: when looking at the json from the Formio widget, it looks like the configuration is unchanged. If one looks at the JSON from the form definition endpoint, then the difference is visible.

### Stappen om te reproduceren / Steps to reproduce

See above

### Verwacht gedrag / Expected behavior

It should not error

**Comment by sergei-maertens** [comment]
Easiest solution is to fix our code that handles this: https://github.com/open-formulieren/open-forms/blob/master/src/openforms/formio/utils.py#L248

Two things catch my attention:

1. `conditional_show in [None, ""]` rather than just checking for None would catch this
2. ` trigger_component_key = conditional.get("when")` -> if `trigger_component_key is None`, also bail out early
