### ISSUE TITLE
Links in form are appended to the baseUrl + 'stap/' URL

### ISSUE THREAD

**Issue by SilviaAmAm** [open-formulieren/open-forms#2465]
### Product versie / Product version

2.0.1

### Omschrijf het probleem / Describe the bug

Den Haag Taiga issue 346 / User story 350

Creating a form with links in the content component or other component (not even sure this is meant to be possible), when filling in this form, they are opened as 'https://open-forms-example.nl/stap/www.link.nl' (while it should have just been www.link.nl).

This does not happen for the  Toelichtingssjabloon.

### Stappen om te reproduceren / Steps to reproduce

Create a form with:
- Toelichtingsjabloon: with a link
- A form step with a content component with a link
- A radio button where one label is `<a href="www.link.com">Link</a>`

Open the form in the SDK:
- Observe that the link on the start page is fine
- When you start the form, both links don't work

### Verwacht gedrag / Expected behavior

- [x] The link in the content component should also open fine.
- [x] HTML in labels should be escaped.

### Screen resolution

None

### Device

None

### OS

None

**Comment by sergei-maertens** [comment]
This is because the link is missing protocol information, which makes it relative to the page.

**Comment by pi-sigma** [comment]
I wonder if this a missing feature or intended behaviour? Clients are likely to forget to specify the protocol (because we don't normally type it in the browser), hence they get the unintended behaviour, which can *seem* like a bug. On the other hand, they might deliberately specify a relative link, and automatically adding the protocol would create a problem in this case.

**Comment by pi-sigma** [comment]
I tried adding different HTML elements (divs, anchor tags) as well as JS snippets to the radio label. The HTML elements are rendered but scripts are not executed (for example, setting the radio label to `<script>alert('foo')</script>bar` will result in "bar" being displayed as the radio label; the script is gone.

It semes that formio distinguishes between *safe* and *unsafe* elements (e.g. anchor tags vs scripts) and escapes the latter but not the former. In light of this, we can consider both points as resolved (though `src/formio/templates/radio.ejs` will still be updated to contain input sanitation via `_userInput`).

**Comment by sergei-maertens** [comment]
Conclusions:

* Form-designers are responsible for including protocol in links to make them fully qualified
* There is no XSS vulnerability since formio passes the labels through the sanitize helpers (which strips dangerous elements via the dompurify lib)
* Because of the above item - including links (and other markup) _is_ officially supported by formio and should be treated as such

**Comment by LaurensBurger** [comment]
This is not limited to the radio labels - any label + description of a component allows html
