### ISSUE TITLE
Deploying a version post 2.0 should not execute the 1.1 -> 2.0 pre-checks

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#2519]
*Writing this ticket without 100% understanding what went wrong*

Real life case is where someone imported a 1.x form in Open Forms 2.0.0 Nothing went visibly wrong (except for the warning in the designer).

Migrating from 2.0.0 to 2.0.1 triggered the pre-checks and caused a failure (I must admit I don't see why this would cause data issues but maybe @sjoerdie can elaborate). This was unexpected because Open Forms was already on 2.0.x

The proper solution is to prevent imports/version rollbacks that cause this issue in the first place, and remove the pre-check.

**Comment by sjoerdie** [comment]
https://github.com/open-formulieren/open-forms/blob/master/src/openforms/upgrades/upgrade_paths.py#L89

**Comment by sergei-maertens** [comment]
two cases to take into account:

* 2.0.x to 2.0.y: checks can be skipped
* 1.1.x to 2.0.y: checks cannot be skipped - upgrading from 1.1.9 to 2.0.3 for example is valid use case (especially because the patch releases have fixed some upgrade issues)

**Comment by sergei-maertens** [comment]
IMO it's not feasible to build all these checks into the form import machinery - not in the slightest because these checks are supposed to prevent database/migration crashes while upgrading (e.g. unique constraints being added).

My expectation is then also that if you do import an old form with these issues, the import itself will fail if constraints are violated. Some checks are bit less nuanced than the actual backend saving logic, e.g. a duplicate form key for WYSIWYG content will be picked up and reported, but not cause a crash because these components do not create variables in the backend.

So the approach in my PR is to not run the checks if you're already on a version equal to or greater than the version with check definitions, for example the check is defined for `2.0`:

* on `1.1.x` it will run
* on `2.0.1` it will not run
* on `2.1` it will not run
