### ISSUE TITLE
Add support for .msg and .dwg file types for attachments

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#2539]
User story: DH 371

Add .msg (application/vnd.ms-outlook) and .dwg (application/acad) to the list of file extensions.

**Comment by pi-sigma** [comment]
I've stumbled upon two problems.

1. The mime type of ".msg" files is reported as `application/CDFV2`. This is similar to the case of ".doc" files, which was the topic of #2520. The check for `application/CDFV2` in `formio.api.validators` happens after the more general mime type check and is never reached because the first check raises a `ValidationError`. This problem can be solved by moving the check for `application/CDFV2` before the general mime type validation.
2. The browser (Firefox/Chrome/Brave) doesn't seem to recognize the "official" mime type for ".msg" files, which is `application/vnd.ms-outlook`. I've seen the issue mentioned elsewhere (e.g. [here](https://stackoverflow.com/questions/62544207/mime-type-of-outlook-email) and [here](https://stackoverflow.com/questions/55687631/which-mime-type-can-i-use-for-msg-file-using-file-object)) but found no general solution. A workaround would be to add ".msg" to the allowed mime types (which the browser recognizes correctly), then in `formio.api.validators` check for the presence of ".msg" in the allowed mime types and replace it with `application/vnd.ms-outlook`.

**Comment by sergei-maertens** [comment]
w/r to 3. - the formio file component does some string splitting on `,` in the `validatePattern` method, so that *should* be supported.

**Comment by pi-sigma** [comment]
@sergei-maertens: that's right, but our backend does not, hence the check still fails in its current form (it fails for both dwg and odt files).

The frontend patch for "msg" files is ready ([PR](https://github.com/open-formulieren/open-forms-sdk/pull/344)) and the backend was easy to fix in this case (I've created a draft PR).

I'm not sure what to do about the backend for "dwg" files (and "odt" files).
