### ISSUE TITLE
Product logic is ignored in summary

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#2709]
### Product versie / Product version

2.0.0 / 2.1.0

### Omschrijf het probleem / Describe the bug

The logic that can be used to calculate the price of a product is ignored by the summary page. The payment amount calculated with the logic is correct. 
In this example we have a rule that sets the price of the product depending the amount of items selected: 
![image](https://user-images.githubusercontent.com/112621537/219013282-f6a1fa75-1487-4c02-88e5-b8579558fa96.png)
We have selected 5 items but the summary shows:
![image](https://user-images.githubusercontent.com/112621537/219013445-9e2e1f90-09bf-4445-8925-2ca5b12362b9.png)
which is the initial product price

Pdf shows the correct product price: 
![image](https://user-images.githubusercontent.com/112621537/219013658-443a12b0-457f-49f0-bf6c-ac67fb440636.png)

And payment amount sent to processor is also correct:
![image](https://user-images.githubusercontent.com/112621537/219013875-51361500-c500-450e-8676-da6075a3dc8f.png)

**Comment by SilviaAmAm** [comment]
How to reproduce:

Create a form with:
- A radio button with values A / B called `radio`
- A user defined var of type number called `total` with default value 0
- A logic rule that says: if `radio == a` change the value of `total` to: `{"+": [{"var": "total"}, 1]}`
- A price rule that says: if `total == 1` then the price is 25

Fill the form:
- select A for the radio
- Go to the summary page: here the price shown is the default price of the product
- Submit the form: see the PDF => Here the price is 25

**Comment by SilviaAmAm** [comment]
There are actually 2 problems here:
1. When the price is being calculated in during the GET to the submission endpoint, the logic is not evaluated. This means that any rule updating the user defined variables (which are persisted only when the submission is completed!) haven't run. Since the price depends on a user defined variable set by logic, the price in the summary is wrong.
2. When completing a submission, the logic rules are evaluated twice in a row: 
    a. here: https://github.com/open-formulieren/open-forms/blob/master/src/openforms/submissions/api/viewsets.py#L239
    b. and here: https://github.com/open-formulieren/open-forms/blob/master/src/openforms/submissions/api/viewsets.py#L250
    This means that logic rules which depend on user defined variables will be using the wrong start value. So the user defined variables will be saved with the wrong value.

The price of the product that is shown in the report and that the user actually pays is calculated after executing the logic once, so it is correct: https://github.com/open-formulieren/open-forms/blob/master/src/openforms/submissions/api/viewsets.py#L246
