### ISSUE TITLE
new components do not generate unique variable in separate steps

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#2770]
steps to reproduce:

1. Create a step
2. Drag a text field component in the form designer (use all the defaults)
3. Add a new step
4. Drag a text field component in the form designer (use all the defaults)
5. Navigate to the variables tab and see there is a validation error

![Image](https://user-images.githubusercontent.com/5518550/221530999-e399c5f0-dbde-4b6e-9c33-7ef45c200a7a.png)

**Comment by sergei-maertens** [comment]
Approach:

-> there are already overrides for the key generation
-> there recently was a patch with the change event in the builder where super wasn't called (related to the translations tab for a component)
-> check if we can pass the react context holding all the form variables to the formio builder options (dynamically, with refs?) so that the key generation can take all existing form variable keys into account

**Comment by sergei-maertens** [comment]
timebox for half a day -> then evaluate the options/approach

**Comment by SilviaAmAm** [comment]
Notes:
The unification of the keys happens in these places:
- On changing an existing component: https://github.com/formio/formio.js/blob/4.13.x/src/WebformBuilder.js#L1387
- On dropping a new component: https://github.com/formio/formio.js/blob/4.13.x/src/WebformBuilder.js#L876
- On pasting a new component: https://github.com/formio/formio.js/blob/4.13.x/src/WebformBuilder.js#L1474
