### ISSUE TITLE
Using empty auth_kvk / auth_bsn as conditionals in the confirmation page/mail doesn't work

### ISSUE THREAD

**Issue by hlmr-erik** [open-formulieren/open-forms#2804]
### Product versie / Product version

2.0.3

### Omschrijf het probleem / Describe the bug

Setting a empty string as conditional leads to:
![image](https://user-images.githubusercontent.com/111565013/222156360-2df80cec-b9b0-4f97-9f25-b3e26dcaaae4.png)

This doesn't work: 
Beste {% if auth_bsn != "" %} {{ achternaam }} {% endif %}{% if auth_kvk !=  "" %} {{ achternaam1 }} {% endif %},

For taking the values from their respective fields ('achternaam' is the ID of the last name field in the BSN version, 'achternaam1' that of the KvK-version). 

However, the same effect can be achieved with this workaround:
Beste {% if achternaam != null %} {{ achternaam }} {% endif %}{% if achternaam1 != null %} {{ achternaam1 }} {% endif %},

where the conditions are taken from prefill values that only get filled when logged in with kvk or bsn. So in all, its not a big issue; but would be more elegant if it could be based on the login options directly.

### Screen resolution

None

### Device

None

### OS

None

**Comment by hlmr-erik** [comment]
Thanks! `{% if not auth_bsn %}` and `{% if not auth_kvk %}` work as expected

**Comment by sergei-maertens** [comment]
@LaurensBurger can you follow up/investigate a bit? This is odd and unexpected.

**Comment by SilviaAmAm** [comment]
I think this is because this is the submission confirmation template. This is rendered after the submission completion, once the registration has been done. By this point, the session is ended. The static variables are not saved, and therefore are not part of the context that is used to render the submission template.

@sergei-maertens do we want to work around it or should I just document it?

**Comment by sergei-maertens** [comment]
Ah yes this makes sense.

Considering that all the static variables need is a `submission` instance, it *should* be possible to provide them to the template context. There is one caveat in this particular situation - the hashed auth attributes will be truthy too even for empty values because empty strings still produce hashes :thinking: 

Maybe a workaround is saving a user defined variable and have the value set through logic after the last step, and then the user defined variable value can be used in the confirmation template? Then we revisit how we want to support this, as from a form designer perspective it's not intuitive that you sometimes can use the static variables and sometimes not.

**Comment by SilviaAmAm** [comment]
It's actually okay without introducing additional user variables => The static variables for the other auth variables than the one with the right auth attribute remain empty strings. Also the task to hash them happens after the registration task, so when the confirmation page is rendered the attributes haven't been hashed yet.
