### ISSUE TITLE
Allow changing of "Download uw inzending als pdf document" string

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#2809]
### Thema / Theme

Form designer

### Omschrijving / Description

DH: 403
This text is unclear for some users, as "pdf" and "inzending" are terms not used in any previous steps of the form

**Comment by sergei-maertens** [comment]
Can't we just use a different string then? "Download het overzicht van ingevulde gegevens" or something like that?

**Comment by LaurensBurger** [comment]
Sure, but the next user wants it to say "Click here and download all your answers", and another might want want: "Download a summary of the form by clicking this link (pdf}" etc. 

The original issue was created with the request for: "Download het formulier dat u heeft verstuurd (pdf)"

**Comment by sergei-maertens** [comment]
I want to discuss this with Joeri to determine how to properly approach this, because translations are also relevant for these dynamic texts and that complicates things. It definitely also complicates for literals that take certain interpolation parameters (e.g. the "pause submission, links expires after X number of days") that I want to have fleshed out before we make changes that we're not happy with on technical level.

**Comment by joeribekker** [comment]
Refinement: We're making this translation possible as global backend option. We're also grabbing this issue to split global configuration to its own endpoint.
