### ISSUE TITLE
ZGW component - Per formulier kunnen bepalen waar (welke ZGW API) het document moet worden weggeschreven

### ISSUE THREAD

**Issue by StefSchots1993** [open-formulieren/open-forms#2859]
### Thema / Theme

Admin

### Omschrijving / Description

Userstory
**Als Beheerder** van  Open Formulieren
**Wil ik** kunnen instellen per formulier waar het aanvraagdocument (pdf) en eventuele bijlagen worden weggeschreven (DRC)
**Zodat** e-Suite gemeenten kunnen bepalen in welke registratie ((OpenZaak/eSuite) of anders systeem) de documenten worden weggeschreven en de zaak kan worden afgehandeld door medewerkers.

NB. Dit is belangrijk voor Gemeenten die het eSuite zaaksysteem gebruiken om Open Formulieren te kunnen inzetten voor zowel gedurende de migratie tijd waarin zowel de eSuite als het nieuwe Zaak afhandel component van de Podium D gebruikt wordt.

![27d1f130-4364-4b81-9c25-024508e3e14c](https://user-images.githubusercontent.com/84498045/224305343-77267910-753d-49fd-932b-7249aa8232dd.png)

**Comment by StefSchots1993** [comment]
https://dimpact.atlassian.net/browse/PF-39

**Comment by joeribekker** [comment]
Besproken met Stef: Dit ticket is direct aanleiding om URLs te refactoren naar identificaties, zodat real-time de passende URL wordt opgehaald.

**Comment by SilviaAmAm** [comment]
After discussion, the things to do are:
- [ ] Decide whether to keep the solo model and link it to multiple ZGWApiSet models or to just have multiple models without the solo.
- [ ] On the `ZaakOptionsSerializer` add a select field to choose the ZGWApiSet to use for the ZGW registration backend.
- [ ] Update the `ZGWRegistration` so that it uses the right ZGWApiSet and the right URLs configured
- [ ] Update the Registratie tab in the component configuration so that the informatieobjecttype come from the right catalogi API.
- [ ] Update the configuration of the Objects API to have its own catalogi API configuration. Make sure that this is used in the Registratie tab of the components.

**Comment by Hugo-ter-Doest** [comment]
@joeribekker @StefSchots1993 Dus je kunt per formulier kiezen naar welke Documenten API het ingevulde formulier moet worden gestuurd? 
Ik vraag dit expliciet na hier omdat er verschillende verhalen rondgaan.

**Comment by Hugo-ter-Doest** [comment]
Thanks!

**Comment by joeridiederen** [comment]
HI @sergei-maertens ; ik geloof dat er ruis is ontstaan. 

Dimpact registreert **niet** via de ZGW-API direct naar Open Zaak. 

Dimpact registreert via de **Objecten-API.** Die methode is loosely coupled, omdat een object leidt tot notificatie die verder verwerkt wordt. Maar, in die registratie-optie kan maar één DRC-API geconfigureerd worden. Dat is voor Dimpact te beperkend, want ze registreren documenten in;
- De eSuite- waar een DRC-API beschikbaar is, voor processen die daarin behandeld worden
- Open Zaak, voor processen die in het ZAC of GZAC behandeld worden

**Comment by sergei-maertens** [comment]
Ah, dat is inderdaad een belangrijk onderscheid, en je conclusie klopt ook. Dit is momenteel niet mogelijk.
