### ISSUE TITLE
Number/currency fields re-fill themselves with value previously saved

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#2903]
### Product versie / Product version

2.1.0

### Omschrijf het probleem / Describe the bug
DH: 454

When a user enters a value in a currency or number field and the users proceeds to the next step, and goes back to the previous step the fields with numbers cannot be emptied. These fields will reset to the previous value after _check_logic. 
Changing the value to something else works, just not null. 
![Peek 2023-03-17 14-17](https://user-images.githubusercontent.com/112621537/225915725-6993f40c-9cd8-482b-8868-f7d3628be347.gif)

### Screen resolution

None

### Device

None

### OS

None

**Comment by SilviaAmAm** [comment]
This happens because Formio removes the value from the form data if we clear the input of number/currency components. On the other hand, if we clear a textfield, the key remains in the form data and the value is set to `""`. See below:
![Screenshot from 2023-03-20 12-59-01](https://user-images.githubusercontent.com/19154114/226332954-6181ee9e-4def-4602-82f7-9755b68209d4.png)
After removing the input from the number field:
![Screenshot from 2023-03-20 12-59-06](https://user-images.githubusercontent.com/19154114/226332957-cb47585c-255d-4ad1-9f7b-60f571e2498d.png)

Then in the backend we merge the incoming data with existing submission data before the logic check: https://github.com/open-formulieren/open-forms/blob/master/src/openforms/submissions/api/viewsets.py#L576
So we re-populate the number field.
