### ISSUE TITLE
Co-signing does not work with mock DigiD

### ISSUE THREAD

**Issue by pi-sigma** [open-formulieren/open-forms#2935]
### Product versie / Product version

2.1.0

### Omschrijf het probleem / Describe the bug

The attempt to log in as co-signer via DigiD currently displays a page with only "missing 'next' parameter".

### Screen resolution

None

### Device

None

### OS

None

**Comment by SilviaAmAm** [comment]
I think the problem is that the CoSign component is not using the `getLoginURL` method to generate the login URL 
https://github.com/open-formulieren/open-forms-sdk/blob/main/src/components/CoSign.js#L40 in the same way that the login buttons do: https://github.com/open-formulieren/open-forms-sdk/blob/main/src/components/LoginOptions/index.js#L20
As a workaround for testing I replaced lines 41 to 53 in the CoSign.js file with
```python
  // add the co-sign submission parameter to the login URL
  const loginUrl = new URL(getLoginUrl(loginOption));
  loginUrl.searchParams.set('coSignSubmission', submissionUuid);
  const modifiedLoginOption = {
    ...loginOption,
    url: loginUrl.href,
    label: (
      <FormattedMessage
        description="Login button label"
        defaultMessage="Login with {provider}"
        values={{provider: loginOption.label}}
      />
    ),
  };
```
But I wonder if the cosign component is also broken for real auth methods?
