### ISSUE TITLE
Selectboxes (selectievakjes) default value is not updated properly

### ISSUE THREAD

**Issue by SilviaAmAm** [open-formulieren/open-forms#2936]
### Product versie / Product version

2.1.x

### Omschrijf het probleem / Describe the bug

Found by Laurens (not reported by a municipality) => Edit: now reported by DH (Taiga issue 476)

### Stappen om te reproduceren / Steps to reproduce

Create a form with:
- A selectboxes with options `A` and `B`
- Save the component
- Edit the component and change the  label of the option to `AA` 
- Save the component => In the variables tab, the default value is `{"":false,"a":false,"b":false}`
- Edit the component and change the label of the option to `AAA`
- Save the component => In the variables tab, the default value is `{"":false,"a":false,"b":false, "aa": false}`

Additional notes:
- If the select boxes component is not updated at all, it looks like the default value is just `null`. This means that the combination of a hidden selectboxes component and a visible required field, cause "required" validation errors to be shown as soon as the user starts a step

### Verwacht gedrag / Expected behavior

The default value should be correct

### Screen resolution

None

### Device

None

### OS

None

**Comment by joeribekker** [comment]
Refinement: This could be fixed by @sergei-maertens refactor of formio builder. Added topic for this. This also implies that the priority of this ticket became lower and was set to milestone 2.2

**Comment by sergei-maertens** [comment]
The new selectboxes component is implemented and undergoing review. The behaviour in the form builder has changed and I think it now does the right thing concerning the reported issue here:

1. For every option you specify, the default value is added if not set yet (set to `false` by default)
2. If you modify the label of an option, the value of the option does one of two things:
    - if `toCamelCase(label) == value` -> the value of the option updates along with the label, irrespective whether it's a new or existing component. This also causes the `defaultValue` to drop the old value and add the new value (with a default of `false` here).
    - if the value was set explicitly and the label is updated, the value is untouched and the associated default value is too (checked or not checked)
3. If you remove an option, the key/value of that option is unset from `defaultValue`

So, `defaultValue` is never `null` anymore and it contains exactly the set of keys as there are option values.

This *does* mean that if you had an option selected by default and change its value, it will now be unselected by default. We currently do not track the old values of options and I'd rather not do that since re-ordering options would severy complicate this implementation.

**Comment by sergei-maertens** [comment]
Verified the old bug report and the new behaviour and I believe this is fixed. @LaurensBurger feel free to test this on our test env from 17:00 onwards and reopen if it's still broken.
