### ISSUE TITLE
Allow steps to become applicable (reverse n/a)

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#2952]
### Thema / Theme

Form designer

### Omschrijving / Description
extension of: #2444 
As a form designer i do not want to show all/any the steps a form might contain. As the forms i design contain a lot of steps that most of the visitors do not need.
I would like the possibility to hide all steps, especially at the "start" of a form and show them only when they become applicable, the complete opposite of how we handle the n/a steps at this time.

Example: form step 1 the user provides input which make makes step 3 4 5 "applicable", but step 2 6 7 remain hidden. 
nowhere in the process will the user see these steps which will create a "cleaner" experience especially with forms that have 10+ steps.

### Aanvullende opmerkingen / Additional context

Current situation:
![image](https://user-images.githubusercontent.com/112621537/229086656-cfef633c-3f56-42c8-b59a-225c9fd28a5f.png)
![image](https://user-images.githubusercontent.com/112621537/229087737-57d99a86-555a-42c0-b282-81c12403628b.png)

With the possibility to only show steps when they become applicable:
![image](https://user-images.githubusercontent.com/112621537/229088540-006a8466-16c3-4a81-bf07-abef0143d9eb.png)
![image](https://user-images.githubusercontent.com/112621537/229088728-914545a3-446c-4a48-b223-564aa23b7272.png)

**Comment by joeribekker** [comment]
Refinement: Als nice to have kunnen we een formulier initieel n/a maken (a la hidden voor velden). De use case om met regel 1 iets n/a te maken, en met regel 2 weer applicable, is niet van toepassing (ik weet ook niet of dit kan met volgorderlijkheid van regels).

Bijvoorbeeld: Als de leeftijd groter is dan 18 jaar, dan moeten er additionele gegevens worden ingevuld die in een stap staan.

**Comment by sergei-maertens** [comment]
yes, let's apply the same logic

**Comment by CharString** [comment]
When I set the that global to hide steps, this form already does the trick:
[dubstep.zip](https://github.com/open-formulieren/open-forms/files/13054809/dubstep.zip)

Almost.. because we don't evaluate the logic on the "start form" page, all steps show. But once you start the form they disappear.
So the smallest change that enables the use case is to not show the progress bar on the start form page.

**Comment by Viicos** [comment]
As discussed with @CharString, maybe @LaurensBurger wants the submission steps to be n/a by default, but this would require a new form logic action doing _Mark the form step as applicable_ (we currently only have _Mark the form step as not-applicable_, which makes sense because they are applicable by default).

> Almost.. because we don't evaluate the logic on the "start form" page, all steps show. But once you start the form they disappear.
So the smallest change that enables the use case is to not show the progress bar on the start form page.

One example use case where this is not enough would be with the following:

Say we have a form step with the following checkbox (unchecked by default):
- [ ] I am younger than 90 years old

and checking this field would then make a bunch of form steps n/a.
But if we evaluate the form logic at the Start Page, all these steps that would be n/a for most people (because the majority is < 90 yo) would still be displayed.

But I don't know if this is common, and form designers can still make things inverted and ask instead: _I am older than 90 years old_ (then, evaluating form logic at the Start Page would be enough)

**Comment by sergei-maertens** [comment]
backend PR still pending
