### ISSUE TITLE
All translation disapear after adding/modifying components in repeating group & field group

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#2958]
### Product versie / Product version

2.1.x
Utrecht, Venray

### Omschrijf het probleem / Describe the bug

Translating some text of a selectboxes component:
![image](https://user-images.githubusercontent.com/112621537/229500087-a5698f9b-d44e-45f2-904a-4c8324ff03d7.png)
- Save translations
- Save the forms
- reload form
Translations are saved correctly

In the same step:

- Add repeating group, or add any field to a repeating group in the same step:
![image](https://user-images.githubusercontent.com/112621537/229500458-00ec8015-d619-466e-95f5-58c7557b9747.png)
- Save form
- Open "selctboxes" with translation:

![image](https://user-images.githubusercontent.com/112621537/229500537-fde6712b-a1b4-4454-b7b1-842c26bb0980.png)
All translations are gone

**Comment by joeribekker** [comment]
Refinement: Translation machinery doesnt work correctly with repeating groups because it uses its own context (i really tried writing down what sergei said).

We would like to fix this within the new form builder unless it becomes really urgent to tackle this beforehand. A rough estimate is that the new form builder is in v2.3 (end of Q3 2023)

**Comment by LaurensBurger** [comment]
@joeribekker while the repeating group in the step triggers this bug the translations for all the components in that step are lost. Which seems like a rather big issue for a form builder in the next 5 months, which would force them to not "touch" any repeating group in a form that has translations because it could result in losing all the translations in that step.

**Comment by sergei-maertens** [comment]
Tasks to solve the root cause by fixing the design:

- [ ] Track translations at the component level instead of entire form definition. This allows different translations for the same base string too.
    - e.g. `component.openForms.translations.nl.label`
    - translate dropdown values, e.g. `option.openForms.translations.nl.label`
    - track fields respective to their component type
- [ ] Migrate form-level translations to component-level (data migration)
- [ ] Ensure there's a compatibility layer for form import/restore
- [ ] Builder: store translations on the component

**Comment by sergei-maertens** [comment]
Tested the implementation by entering a value for all translatable fields for all possible components and checking how it renders in the frontend, and I could not find any issues.

**Comment by joeribekker** [comment]
💯
