### ISSUE TITLE
Prototype the static analysis

### ISSUE THREAD

**Issue by CharString** [open-formulieren/open-forms#2959]
* [x] Implement a type inference algorithm preferably M as it was [proven](https://dl.acm.org/doi/10.1145/291891.291892) to terminate earlier than 𝒲 and give more pinpointed errors
* [x] Implement a function `parse` that takes a JsonLogic expression and returns an expression that `M()` can take.
* [x] Implement `type_check`
* [ ] support the variadic versions of some JsonLogic operators (e.g. "<", "+", "in")
* [x] support return type polymorphism*

*return type polymorphism in python notation:
```python
T1 = TypeVar("T1")
T2 = TypeVar("T2")
def if_operator(condition: Bool, then: T1, else_:T2) -> Union[T1, T2]:
    ...
```

**Comment by joeribekker** [comment]
Refinement: @CharString plans a presentation.

**Comment by joeribekker** [comment]
Refinement: Chris gave a presentation; seems to work pretty well. There are a few cases that don't provide the definitive type but we don't see this as a problem. Discussed was were the type inference should work. Consensus was to made this work on the frontend and (maybe) on the backend using an node server. So, the work Chris did needs to be converted to typescript but there seems to be a typescript library already. Chris contacted the author to see if we can use this.

So, TODO:

* Typescript thing still needs a parser for JSON-logic and default context with type 
* We should introduce the `inStr` operation to distinct between `in` for arrays and `in` for strings.
* Design an interface so that Open Formulieren can show human readable feedback
* Figure out an interface so you can set the variable type for user defined variables from inference.
