### ISSUE TITLE
As form designer I want to require payment before the form is submitted/registered

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#3005]
### Thema / Theme

Frontend

### Omschrijving / Description

Although the original use case for payments was that payments are not required before submitting (ie. payment can also be done later or at the service desk), some organisations want to require payment before the submission is registered, to prevent an extra workflow/check to see if payment was made - which takes time to process.

For this, we need to restructure the post-submission flow by doing the payment beforehand. Basically saying a succesful payment means the form is successfully submitted. Keep in mind, the original flow should still be possible.

![1681813426930](https://user-images.githubusercontent.com/96970/232749351-bb391beb-c91f-4d8f-aa36-3c6d6dced3c5.jpg)

Before splitting this in tasks, I see overlap between this and co-signing (#1530) where we wait until the submission is co-signed before pushing it towards registration. The same can be done here. You can complete the submission (in open forms) but its not pushed to registration until payment is received.

In both the new co sign and new payment flow, there is a "final confirmation page". This page can show the zaaknumber and the final PDF (where it says paid and/or co-signed). Maybe we should offer a concept PDF before co-sign/payment is done to keep the flow clean but not sure about this.

**Comment by LaurensBurger** [comment]
This enhancement has also been requested by:
lv, wdw, SED, utr

**Comment by SilviaAmAm** [comment]
Flow:
- User completes submission
- In src/openforms/registrations/tasks.py (register_submission) check the fields:
	- payment_required
	- user_has_paid
	- wait_for_payment_to_register (to be added)
  If payment_required == true, user_has_paid == false and wait_for_payment_to_register == true, skip registration.
  Otherwise register submission.
- Send confirmation email with details of the submission and that payment is required (should already include a link to pay)
- User pays
- Completion chain is triggered:
	- If submission has wait_for_payment_to_register==true:
		- Register submission. 
		- New confirmation email is sent saying that the payment was received and that the registration has been completed.
	- If submission has wait_for_payment_to_register==false:
		- Update the payment status in the registration backend. 
		- Still send a confirmation email that payment was received.

To do:
- [ ] Add a general config field wait_for_payment_to_register
- [ ] Update tasks.py to skip registration in case payment has not been done yet
- [ ] Update confirmation email template src/openforms/payments/templates/payments/payment_link.html to say something like "payment required of X euro. You can pay here: link. When payment has been received you will receive another confirmation email".
- [ ] Investigate if there is a way to combine the triggering of tasks chains, so that it is easier to follow where tasks are being started.
- [ ] Add a task for post payment which will either register the submission or update the status in the registration backend and then send a confirmation email.
- [ ] Document new flow
- [ ] Test a form with both co-sign and payment

**Comment by hlmr-erik** [comment]
In this new flow, is it possible to require payment before the form is submitted? As users can easily miss text about a required payment, and having successfully submitted the form might be in the supposition that their requested product is forthcoming; we'd like to be able to put a hard limit on sending the form.

**Comment by joeribekker** [comment]
@hlmr-erik this is indeed what should be possible after this user story is done.

**Comment by hlmr-erik** [comment]
Great! That was what I initially thought this story to mean, but then got confused reading the specifics. From those it seemed that the form could still be sent, just that the registration process further down the line would be held up until payment.

**Comment by joeribekker** [comment]
@hlmr-erik You made me doubt and double check with the developer. It is, as you indicate in your last comment.

So this:

> we'd like to be able to put a hard limit on sending the form.

Is not possible.

**Comment by sergei-maertens** [comment]
Refactor done, now the rest still :grimacing:
