### ISSUE TITLE
Repeating groups - not saving causes form to get stuck

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#3096]
### Product versie / Product version

2.x.x
internal: Venr 56 

### Omschrijf het probleem / Describe the bug

When a user adds i reapeating group item but does not save or cancel this addition, the form will not continue to the next step.
![Peek 2023-05-19 09-31](https://github.com/open-formulieren/open-forms/assets/112621537/d2e9512d-72d4-4487-8bc7-81c13e528b66)

example, "volgende" is available, but clicking does not trigger any event:

there should either be a warning about the item being unsaved, or the next step should load.

**Comment by joeribekker** [comment]
Refinement: Discussed, needs fix :0

**Comment by SilviaAmAm** [comment]
Can reproduce on latest (SDK 5cb1b584845fb6526aeadc1ac3e0d2d6501fd2f1). When clicking on the next button with an unsaved open iteration, the console shows:
```
Uncaught (in promise) TypeError: n.errors[0] is undefined
```

**Comment by SilviaAmAm** [comment]
What was happening:
- The function `checkComponentValidity` is called to validate the editGrid (https://github.com/formio/formio.js/blob/v4.13.13/src/components/editgrid/EditGrid.js#L969). This makes a call to super.
- The `super.checkComponentValidity` checks the editGrid 'as a whole': it checks the 'required' validator, the max length validator... If the component as a whole is valid, then it schedules a callback to `setComponentValidity`, which will clear errors on the component.
- The `checkComponentValidity` of editGrid now checks if each row is valid and if there are any open/unsaved rows. Since it is the case, it sets the component validity (note: it does it syncronously, it doesn't schedule a callback like the super.
- The callback of the super executes. This clears the error on the component (but it must miss something somewhere because the form submission is blocked, but no error is visible).
