### ISSUE TITLE
Add xml header to digid metadata

### ISSUE THREAD

**Issue by sjoerdie** [open-formulieren/open-forms#3103]
### Thema / Theme

Frontend

### Omschrijving / Description

`<?xml version="1.0" encoding="UTF-8"?>`

### Added value / Toegevoegde waarde

<?xml version="1.0" encoding="UTF-8"?>

### Aanvullende opmerkingen / Additional context

Required by logius.

**Comment by sergei-maertens** [comment]
Discussed with Sjoerd - applying this patch for the stable/2.0.x release series is too involved due to breaking changes in the underlying library. The workaround is to generate the metadata on the CLI and manually prepend the xml declaration.

For stable/2.1.x I think I can safely upgrade the library and I'll create a PR for that.

For the upcoming 2.2 release, the library needs to be ugpraded for new features anyway, so that's happening as part of #2860
