### ISSUE TITLE
Service fetch: allow setting "expected_status" for status codes that are not 200

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#3106]
### Thema / Theme

Form designer

### Omschrijving / Description

As a form designer i want to set the "expected_status" for the response my service fetch request makes. 
At the moment this can only be 200, but POST requests typically return a 201.

**Comment by alextreme** [comment]
Discussed with Laurens:

https://github.com/open-formulieren/open-forms/blob/7d44b60888510509ce2c9aabfeff3cef245aa775/src/openforms/submissions/logic/service_fetching.py#L41

client.request(**request_args) should be given the parameter `expected_status=201` in this situation. Unfortunately there isn't an option in zgw_consumers/zds_client to pass along multiple expected statusses (ideally you would want to accept all 2XX responses instead of only a fixed status code of 200).

A few options:
- Expand zgw_consumers/zds_client to be able to pass a list of expected status codes
- Expand zgw_consumers/zds_client to be able to ignore the expected status code
- Expand the service fetch client to be able to configure the expected status code

**Comment by sergei-maertens** [comment]
Obsoleted since we've switched away from zds-client to ape-pie, which doesn't perform such checks. Instead, we call `response.raise_for_status()` which accepts 2xx and 3xx responses.
