### ISSUE TITLE
Insufficient visibility of tooltip text

### ISSUE THREAD

**Issue by hlmr-erik** [open-formulieren/open-forms#3209]
### Product versie / Product version

2.*.* (latest)

### Omschrijf het probleem / Describe the bug

Right now, there is no background and border around the tooltip, making it hard to make out what is written. Apart from that, the menu covers the text.

![Image](https://github.com/open-formulieren/open-forms/assets/111565013/0701d968-3a41-4e94-825c-1785b8eb8ad0)

&nbsp;
&nbsp;

PS. It is possible to add HTML to the tooltip for added styling, might be helpful to mention as well in documentation.
![image](https://github.com/open-formulieren/open-forms/assets/111565013/667b7ada-7a59-41d1-81e7-6214d9a3861e)
![image](https://github.com/open-formulieren/open-forms/assets/111565013/e6f9368e-225e-4c0f-8bc4-6500eac48a41)

### Screen resolution

1920 x 1080

### Device

Desktop

### OS

Windows

### Browser

Firefox

**Comment by sergei-maertens** [comment]
W/r to the HTML in tooltip - that's something that is handled by Form.io and not something we want to draw attention to, particularly because it can cause issues with Content Security Policy.

When we implement the React variant of this in the form-builder, we will definitely lean to proper HTML escaping (and for extra formatting, we'd rather opt for markdown as text format which is then converted to HTML).
