### ISSUE TITLE
Removing variables/fields can cause Logic tab to crash

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#3422]
### Product versie / Product version

2.3.0

### Omschrijf het probleem / Describe the bug

Sentry: 337920
Utr: 112

Removing fields, groups or steps that are in use in the logic tab can cause the logic tab to crash, in turn breaking the form. 
The only way to fix it is to export the form, remove logic rules that contain the unused variables and import again.

When trying to import a form in this state you see the error: 
`Er is iets foutgegaan bij het importeren van formulier: {'json_logic_trigger': [ErrorDetail(string='De opgegeven variabele is niet aanwezig in het formulier', code='invalid')]}`

unsure about conditions on how to reproduce

**Comment by sergei-maertens** [comment]
Refinement:

1. We should try to reproduce this and
2. fix the root cause and then
3. make sure we wrap our logic rules in an `ErrorBoundary` to prevent the entire tab from crashing if there's an issue (these sort of bugs will probably keep happening). The error boundary needs to be set up so that we still have the icons available so any broken rule can still be removed to reduce the impact of bugs.

Possibly we could display the JSON definition as well so that it can be copy-pasted to "back up" complex rules.

**Comment by sergei-maertens** [comment]
Silvia: saving the form first saves the variables and then it goes wrong in the saving of the logic rules, so this could lead to a broken state in the frontend. To confirm.

**Comment by sergei-maertens** [comment]
Scope this to reproducing it first and then we decide the importance/prio of a fix.

**Comment by SilviaAmAm** [comment]
Steps to reproduce:

1. Create a form with 2 steps, with a textfield each.
2. Add a logic rule: if `textfield2` is equal to "bla" block going to the next step.
3. Make this rule active only from step 2.
4. Remove step 2.
5. Go to the logic tab: everything disappears 😢
