### ISSUE TITLE
E-mail: "BadHeaderError: Header values can't contain newlines "

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#3448]
### Product versie / Product version

2.3.0

### Omschrijf het probleem / Describe the bug

Long subject lines (70+ chars) get `\n` added them and django-yubin will not allow the e-mail to be sent. 
sentry: 336550 
This results in a succesful submission: Registratieplugin "E-mail registratie" (email) meldt: Registratie geslaagd.

**Comment by sergei-maertens** [comment]
1. Report to upstream django-yubin
2. Contribute a patch - they are receptive

**Comment by SilviaAmAm** [comment]
What is happening:
- During queuing of message, django Yubin calls email_message.message() https://github.com/APSL/django-yubin/blob/master/django_yubin/__init__.py#L35 to get the message data as a string so that it can be saved to the database. When processing the headers, django core email module calls https://github.com/django/django/blob/main/django/core/mail/message.py#L74. This has the effect of adding `\n` characters to long subject lines.
- The resulting message is saved into the database (and it contains `\n` in the subject).
- When the queued task is picked up, the message is recreated before being sent https://github.com/APSL/django-yubin/blob/master/django_yubin/engine.py#L54. The checks for the new lines are done and they fail: https://github.com/django/django/blob/main/django/core/mail/message.py#L59

**Comment by SilviaAmAm** [comment]
Yubin PR: https://github.com/APSL/django-yubin/pull/71
