### ISSUE TITLE
progress indicator: word-break: break-all looks bad. 

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#3450]
### Product versie / Product version

2.2.0 - 2.3.0
venr: 73

### Omschrijf het probleem / Describe the bug

![image](https://github.com/open-formulieren/open-forms/assets/112621537/36e80dab-b9b7-4def-bda5-e642999f8d13)
Should be break-word:
![image](https://github.com/open-formulieren/open-forms/assets/112621537/a17e065b-e6d1-4bb1-9b30-eaf6961a3c8d)

**Comment by sergei-maertens** [comment]
This was a deliberate decision from DH because they have long words that otherwise overflow. The documentation mentions you can use soft hyphens on https://open-forms.readthedocs.io/en/stable/manual/forms/basics.html#formulier so if we make the suggested change, other clients will have to update their names to add soft hyphens.

**Comment by LaurensBurger** [comment]
hyphens: auto;
~~word-break: break-all;~~

looks like it solves both long words and long titles.
![image](https://github.com/open-formulieren/open-forms/assets/112621537/28a45950-0930-4869-b147-2d194bfcc677)
![image](https://github.com/open-formulieren/open-forms/assets/112621537/e3dda11d-53d5-4b59-aa7b-22b319d86852)

**Comment by sergei-maertens** [comment]
https://caniuse.com/css-hyphens also looks promising

**Comment by joeribekker** [comment]
Refinement: Marking as improvement but sounds like there is an easy way to make it better, so picking it up.
