### ISSUE TITLE
Allow setting custom Ogone "Title" and "Com"

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#3457]
### Thema / Theme

Admin

### Omschrijving / Description

RID: 146
VENR: 105
DH: 717

As a admin i want to set the "title" that is sent to Ogone with a payment request. 
Currently this is "inzending: {{public_reference}}: `TITLE: Inzending: OF-EC7WWT`, `COM: Inzending: OF-EC7WWT`

But i want to be able to set this to any var. 

This will allow to make bank statements more understandable to party's who do not have access to submissions via their reference. for example a billing dept.

**Comment by joeribekker** [comment]
Refinement: Needs stakeholder.

**Comment by joeribekker** [comment]
Dimpact will pick this under PF-129

**Comment by LaurensBurger** [comment]
DH also requested this feature

**Comment by joeribekker** [comment]
Refinement: If this is only globally configurable, using only static vars: 2 days, if per form: 3 days. It eas mentioned to use a dropdpown of variables but does this give enough flexibility, otr should it be a template field, or ...

**Comment by sergei-maertens** [comment]
Additional clarification after talking to Bob:

* Being able to set COM and TITLE on a per-form basis is enough, there's no need to support any variables in the global configuration for the payment reference
* An image of a PDF with transactions was shown, which confirms that the COM attribute is what's included in these statements, and responsible for routing the payment to the right department
* Variables are indeed required to be supported even in this case, because you can have different context (e.g. "scheidingsakte" or "huwelijksakte") that is relevant for the routing
* The max limit is 100 chars, alphanumeric (see https://support.legacy.worldline-solutions.com/en/help/parameter-cookbook), so we will truncate this because we cannot upfront validate the length of variables (and also likely need to strip accents etc.)
