### ISSUE TITLE
"/" in form title causes submission to fail: SuspiciousFileOperation in generate_submission_report

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#3470]
### Product versie / Product version

2.2.x - 2.3.0

### Omschrijf het probleem / Describe the bug

When a form title contains a "/" this title is used as is to store sumbission pdf's which it cannot do. 
Subsequently the registration is unable to find the pdf

form title: foo/bar
dir_name = submission-reports/2023/09/07/foo
file_ext = '.pdf'
file_name = 'bar.pdf'
name = 'foo/bar.pdf'

SuspiciousFileOperation: Storage can not find an available filename for "submission-reports/2023/09/07/foo/bar_wb1x7PV.pdf". Please make sure that the corresponding file field allows sufficient "max_length".

sentry: 332615

**Comment by joeribekker** [comment]
Refinement: We should use the slug. Weird that it didnt yet because then more characters would make this fail?

If this is caused by the templating (prefix/postfix, file name that you can configure, whatever) there needs to be a slugify operation afterwards OR it should not even be allowed to use these characters in the first place.
