### ISSUE TITLE
Unable to remove Graph service/registration if there is just 1 service

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#3548]
### Product versie / Product version

2.2.0 - 2.4.0

### Omschrijf het probleem / Describe the bug

The Microsoft Graph registration, once set, cannot be unset which results in a loop where you cannot remove the service which is selected. Meaning there will always be a Graph service stuck in your configuration.
![image](https://github.com/open-formulieren/open-forms/assets/112621537/e067dca4-5a61-46d3-9e8c-b2cbf07a86b4)

**Comment by joeribekker** [comment]
Refinment: @LaurensBurger is this caused by custom permissions or are you superuser?

**Comment by Viicos** [comment]
After investigation:
- A permission issue is fired because a singleton model can't be deleted by anyone (`has_delete_permission` always returns `False`).
- This is not only the case "if there is just 1 service", the error happens if the service is being used in the configuration singleton model. This configuration singleton model also sets `on_delete` to `PROTECT`, so the issue may come from here as well.
