### ISSUE TITLE
Safari: "Next" step button disables after check_logic when a step has a content component with a color tag in the html

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#3572]
### Product versie / Product version

2.3.2

### Omschrijf het probleem / Describe the bug

on webkit browsers the "Next" button seems to always disable itself after check_logic.

Compared chrome to safari all network requests look identical. 

Can reproduce by adding a text with color to a content component:
![image](https://github.com/open-formulieren/open-forms/assets/112621537/7c12276b-a0da-4134-82b9-07cd120d5d2c)

No color:
![image](https://github.com/open-formulieren/open-forms/assets/112621537/2cb2c3b9-20e6-4a8d-a1ac-582bb56b13eb)

Other styles:
![image](https://github.com/open-formulieren/open-forms/assets/112621537/418e8ceb-fc97-4553-a7fc-23a68a59ab91)

**Comment by sergei-maertens** [comment]
On Linux machines you can use the "GNOME Web" browser which is webkit based.

**Comment by Viicos** [comment]
After some debugging:

No matter if there's a color tag in the HTML or not, it seems the `dispatch` call with action `BLOCK_SUBMISSION` is fired twice (on webkit only). The first one is made in [`evaluateFromLogic`](https://github.com/open-formulieren/open-forms-sdk/blob/51734da95aa5b184ad20c023986d60a5f823adcf/src/components/FormStep/index.js#L454-L457), and the second one (immediately after) is seemingly fired from nowhere.
I couldn't find any relevant issue related to Redux that could explain this unexpected second call.

The reason it fails when there's a colored text element is that for some reason this triggers `onFormIOChange` another time (even on non webkit), and this time `canSubmit` (which directly comes from the sate) is `false` because of the unexpected `BLOCK_SUBMISSION` dispatch.

So essentially having a colored text element just "reveals" the real underlying issue
