### ISSUE TITLE
As a municipality I want to register part of the submission data as a Zaak in ZGW and an object in the Objects API

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#3601]
... so that I can relate the object to the created Zaak.

Ref: Utr 138

**Comment by vaszig** [comment]
I am leaving here a conclusion and some thoughts after some investigation concerning the submission flow and the phase where this is completed (the image has `pre_register` and `register` methods taken from the Objects API and added as quick overview of the flow):

- We want to send submission data to the Objects API and to the ZGW APIs.
- Ideally this should be more dynamic and try not to stick to only these two choices. This makes this task a bit tricky.
- Now, we have a chain of celery tasks which retrieve the registration backend and perform a series of actions.
- Not a nice solution yet from my end, the only thing which I don't know exactly the impact, would be to be able to select the registration backends we desire and perform the already implemented tasks for each one of them (This makes me think though the possible performance issues).

Because of these, a meeting with @joeribekker and @sergei-maertens  will be needed for further discussion and more ideas.



![Image](https://github.com/open-formulieren/open-forms/assets/63058071/77036205-9745-41f5-a6c7-c119344f509a)
