### ISSUE TITLE
Detect more problems and add them to the email digest

### ISSUE THREAD

**Issue by sergei-maertens** [open-formulieren/open-forms#3725]
Target audience: functional administrators
Goal: avoid things breaking silently (things will break)

**Things that go wrong during runtime**

- [x] All submissions with failed registration status (or a handy admin link to filter those)
    - check `TimelineLog` from past 24 hours
    - aggregate on form title/name + number of failed submissions + clickable link to submissions admin with preconfigured filters, e.g. `/admin/submissions/submission?form=123&state=failed&from=24hAgo`
    - (add submission filter for 'past 24 hours')
    - when was first & last failure in the past 24 hours
    - example text in email: `Aanvraag subsidie registratie gefaald: 3 times between 14:03 and 15:24 in the past 24 hours`

- [x] Log failures (e.g. from prefill) (e.g. create log record that we can filter on) etc. & include how many failed each day (and aggregate problem)

See also #3999 which may overlap for (Prometheus) metrics.

* The page to view these relevant log records should include/display sufficient context, like which form(s) are affected, timestamps..., type of error (maybe)?
* Pointers to where people can look to investigate
    - logs
    - tip to enable request logging?

**Things that can go wrong/cause support overhead because of broken configuration**

- [x] If `addressNL` components are used in (active) forms, then the BRK client must be configured properly. If this is not the case, include it as a problem that needs attention. (from github PR review comment: )
- [x] Deriving street/city from postal code/number without configuring the BAG API
- [x] Are forms still valid or not? 
    - Registration backend configuration
    - Broken logic rules (fields that no longer exist)
    - ~~Deprecated components~~ (in screen warning better?)
- [x] (zgw consumers) services / configuration overview -> run test periodically & include result?
    - certificate checks (inspecting error responses + educated guesses/suggestions)
    - warn of certificate expiries (when <= 2 weeks to go?)
    - host connection / credentials
    - configuration complete or not

**Comment by alextreme** [comment]
Discussed with Laurens:
- Daily digest with failed registrations -> doesn't really require configuration options, if >0 failed include in the digest. Do we want to show all from the last day or all in total?
- Are email submissions being retried at all (for instance when mailserver is down)? -> yubin retry task? We are unsure if this is still an issue.
- If there are many pending submission-payments without completion?

Issues that would warrant a quicker warning than via the daily digest:
- Would also be useful to receive a notification if the BRP or another connection is down -> if more than 5x/10x 4xx/5xx/exceptions logged via outgoing log requests within a 30 minute timeframe, then send a warning email immediately? (in line with the BRK client issue Sergei mentioned)
- If more than X failed submissions (5 or 10) within a certain timeframe, then send a warning email immediately? -> this to avoid the situation where a ZDS/ZGW connection is down for a whole day

Underlying issue is that we are logging information, however failing situations aren't being raised as an alert. Sometimes admins only discover after 60 days that submissions have failed. So starting with expanding the digest with the failed submissions would be a good first step and that after that we expand the digest iteratively based on incidents we encounter

**Comment by sergei-maertens** [comment]
> Would also be useful to receive a notification if the BRP or another connection is down -> if more than 5x/10x 4xx/5xx/exceptions logged via outgoing log requests within a 30 minute timeframe, then send a warning email immediately? (in line with the BRK client issue Sergei mentioned)

Note from me - we must be careful that we don't re-implement Sentry here, it already has these sort of alerting rules built in. See what we can re-use? OTOH this is really an observability thing that Open Telemetry can/should help with!

**Comment by alextreme** [comment]
> > Would also be useful to receive a notification if the BRP or another connection is down -> if more than 5x/10x 4xx/5xx/exceptions logged via outgoing log requests within a 30 minute timeframe, then send a warning email immediately? (in line with the BRK client issue Sergei mentioned)
> 
> Note from me - we must be careful that we don't re-implement Sentry here, it already has these sort of alerting rules built in. See what we can re-use? OTOH this is really an observability thing that Open Telemetry can/should help with!

We considered the same, however note that this is a digest and alerting for OF admin-users. Laurens and I don't want to be the 'doorgeefluik' if there are problems with a certain OF instance.

But what we could come to is that OF provides the daily digest, but if you need to be more on top of things regarding alerts that you can hook up your OT environment with your OF install.

**Comment by sergei-maertens** [comment]
Yeah something like that, or since most observability solutions have notification systems in place, it could be wired up to ping-back to the OF instance which in turn sends a digest/alert email to the configured addresses

thinking out loud here - nothing is set in stone!

**Comment by sergei-maertens** [comment]
not done yet :)
