### ISSUE TITLE
Form builder - Datetime field empties itself when a invalid date is entered

### ISSUE THREAD

**Issue by vaszig** [open-formulieren/open-forms#3755]
Occurs when you set a validation, e.g. date/datetime must be in the future and then enter an invalid value. The date field still displays the invalid value and shows the validation error, the datetime field removes the invalid value and displays no validation error.

The behaviour is consistent with the old form builder

Part of #3733

**Comment by SilviaAmAm** [comment]
Steps to reproduce:
- Create a form in the admin with:
   - A date component with validation 'min value' => in the future
   - A datetime component with validation 'min value' => in the future
- In the SDK, fill in the form.
   - For both components, enter a date/datetime in the past
   - Observe that the date component shows a validation error, while the datetime component empties itself.

The behaviour for the date component was fixed in this issue: https://github.com/open-formulieren/open-forms/issues/3443

**Comment by SilviaAmAm** [comment]
Work in the form builder still needs to happen

**Comment by SilviaAmAm** [comment]
Upgrading form builder in backend needs to be done
