### ISSUE TITLE
Retrieving the available forms via the Formulieren API (/api/v2/forms) is slow

### ISSUE THREAD

**Issue by alextreme** [open-formulieren/open-forms#3825]
### Thema / Theme

API

### Omschrijving / Description

We noticed in OIP 1768 that the /api/v2/forms endpoint is slower than our 5-second timeout, it is now 10-12 seconds on average.

We'll increase our timeout duration as a workaround and the OF testenvironment has quite a few complicated forms, but would it be possible to speed up this endpoint?

The integration in OIP uses Joeri's OF client: https://github.com/open-formulieren/open-forms-client-django 

![image](https://github.com/open-formulieren/open-forms/assets/226839/5cc23642-4da6-4659-a839-7ded365a7173)

**Comment by joeribekker** [comment]
Refinement: I noticed this as well when testing the library. This will be fixed by making a public API endpoint that only contains the needed info as described in #3838

**Comment by SilviaAmAm** [comment]
Discussed with Sergei. The requirements are:
- A category list endpoint
- A form list endpoints exposing:
   - The form name, internal name, slug,  uuid (open-forms-client uses uuid or slug).
   - A query param `category` to filter on the category
   - Results nested under `results` (so that pagination is easier to add)
   - Not include deleted forms

These endpoints should:
- not have pagination
- Have token auth
