### ISSUE TITLE
Two forms with a re-usable form definition "sometimes" leads to an incorrect form in one of the two

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#3881]
We found this issue when figuring out why voorletters was suddenly not working in the prefill when migrating from 2.4.3 to 2.4.5.

The client said it didn't work. Made the initials field writable (it was readonly) so it could be filled, and saved the form (this step was a re-usable form definition). When we tested it, it worked. Silvia suggested it could be related to a variable not being created and it was then created when the form was saved, making the form function.

This might also be the case why a re-usable form definition works in form A but not in form B, after the form definition is changed in form A.

**Comment by sergei-maertens** [comment]
Refinement: suspicion is that updating a form variable via form X does not result in the same update being saved on form variable in form Y that also happens to use the same reusable form definition.

Form variables are persisted in bulk in one transaction (`variables_bulk_update`).

Remarks: this is bigger than just the prefill-configuration being out of sync, it also affects logic, registration, e.g. when:

- a variable is deleted
- a variable is renamed

We have a warning in the frontend that says X number of forms will be affected by changing the reusable form definition. However, because prefill is configured on the component itself (and synced/copied to the variable), the impression is that this will automatically apply to all forms using this form definition and the warning does not absolve us from properly handling this.

So, we scope this to sychronizing variable configuration for this particular form definition (i.e. there is a match on form_definition FK, we nuke existing variables and recreate the new ones).

Tasks:

- confirm this theory
- if confirmed, synchronize form variables in *other* forms -> kick off celery task after `variables_bulk_update` and use the `form_definition` information of each variable to figure out which forms need to be updated. 
- take into account the submission variable recoupling too.

**Comment by sergei-maertens** [comment]
Backport label added - let's aim for this, but we should not compromise the fix/implementation to make it backportable. Manual fixing is possible, so needs-backport is to be nice to customers :)
