### ISSUE TITLE
FE logic: When the value of number field is used to trigger visibility, components are emptied when "Clear on hide" is checked

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#3964]
### Product versie / Product version

2.4.3 - 2.6.0

### Omschrijf het probleem / Describe the bug

When the value of number/currency field is used in FE logic and the component that is made visible has: "Clear on hide" checked, the values entered into this field will be removed at validation (check_logic)

`if Getal = 0 show Tekstvlak`

![pooof](https://github.com/open-formulieren/open-forms/assets/112621537/63251bd9-5a15-43de-b11c-d828297d113f)
![Kooha-2024-03-01-21-23-53](https://github.com/open-formulieren/open-forms/assets/112621537/ce9766c0-4016-49d2-8ecc-bd0c4c3635d5)

If a different logic is used on the same Number component like: `if not Getal hide Tekstvlak`
This bug does not occur, so it seems to be specific to the value in the number field

# Discussion:

We changed the formio-builder so that for new forms the conditional value is not saved as a string but as a number.

However, this will not fix existing forms that have a configuration where the conditional value is already a string. For fixing these forms there were 2 possibilities:
- Migration: find forms that have this problem and fix the configuration. This migration is quite complex and would also have to run on import.
- Bandaid fix in the logic (like for checkboxes: https://github.com/open-formulieren/open-forms/blob/1d22bdc733f5fa854f4d07cfe357e62e35a82db0/src/openforms/formio/utils.py#L358). This is quite easy, although care needs to be taken with the int/float casting.

Considerations:
- Writing the migration feels like the 'right thing':  new components have fixed behaviour and you don't want to carry along a legacy fix forever. It's better to root it out as soon as possible.
- Backporting the migration is tricky

Conclusion:
- Migration for master
- Bandaid for backport

In addition:
- See if you can fix checkboxes so we can remove the bandaid fix in master

**Comment by sergei-maertens** [comment]
So this can be worked around by editing the JSON? I'm trying to figure out of this needs backporting.

And a patch would be in the form builder to cast the value of `eq` to the respective type of the referenced component in `when`?

**Comment by SilviaAmAm** [comment]
Yes, if the `"0"` is changed in the json to `0`, it works as expected.

I was wondering if in the form builder, the field for the conditional value should have the same type as the component selected:
![matching-type](https://github.com/open-formulieren/open-forms/assets/19154114/badb96dd-4a96-4bbc-b130-d5b1cadf41ce)

Then there would be no need to cast I think?

**Comment by sergei-maertens** [comment]
The casting logic should be done based on the component type, since the component type determines the data type, or am I misunderstanding something? 

The option labels are `{component.label} ({component.key})` here, the value between brackets is not the type of component :) Perhaps that is causing some confusion?

**Comment by SilviaAmAm** [comment]
What I meant is:

If you select a component of type `number` in the dropdown, then the input field below (field with label `has the value`) would be:
```html
<input type="number" ... >
```
instead of a text field. So the type of the input would depend on the component selected for the condition. That way it would have the right type of value without casting.

**Comment by sergei-maertens** [comment]
Ah right, that makes sense! Note however that it's Formik that takes care of casting the string values to numbers then, and this would need to apply to component types `number` and `currency` both, but yes, your approach is much more elegant :)

**Comment by SilviaAmAm** [comment]
I thought a bit more about it:

We can't really rely only on the type of the chosen component (if the component has `multiple = True` then it is an array instead of whatever other simple type). So we would need a field like the `DefaultValue` react component that each component has in the edit form.

However, this would break the logic check for the selectboxes. These have a value that is an object, but in the 'simple conditional' configuration you enter a string. Then, Formio does some special checks when evaluating the logic. For example, if the value is `{"valueA": true, "valueB": false}` and the conditional is:
```json
"conditional": {
   "eq": "valueB", 
   "show": true, 
   "when": "selectboxesComponent"
}
```
then formio does some special check to see if `valueB == True`.

So more thinking needed :thought_balloon:
