### ISSUE TITLE
Unable to submit a form with a textfield without max length specified

### ISSUE THREAD

**Issue by Viicos** [open-formulieren/open-forms#4016]
### Product versie / Product version

latest

### Omschrijf het probleem / Describe the bug

The following code:
https://github.com/open-formulieren/open-forms/blob/50ff077a2e3d5901185311f71e58e30aa6a9f128/src/openforms/formio/components/vanilla.py#L161-L162

fails as `max_length` is an empty string, while the DRF serializer excepts the value to be an int, resulting in a:

`TypeError: '>' not supported between instances of 'int' and 'str'`

when making a submission.

### Stappen om te reproduceren / Steps to reproduce

Create a form with a text field, not max length specified

Try to submit for this form

### Screen resolution

None

### Device

None

### OS

None

**Comment by sergei-maertens** [comment]
Couple things happening here that are problematic:

1. the empty value being an empty string in the formio side is weird, it doesn't match their own type definitions: https://github.com/formio/formio.js/blob/4.13.x/types/components/schema.d.ts#L184
2. the form builder might have to normalize this
3. we need additional robustness checks in our backend code because formio can't behave
4. we need a data migration to correct this (ideally just remove/unset the key if nothing is specified, since the type definitions do not allow for `null`)

**Comment by sergei-maertens** [comment]
What I don't understand though, is that the formio builder set a default value of `1000` for max length :thinking: how is that turned into an empty string?

**Comment by sergei-maertens** [comment]
`type: number` has the same issue with the `min` and `max` fields

**Comment by sergei-maertens** [comment]
current master in formio is just broken in this regard: https://github.com/formio/formio.js/blob/31c670d8b4126ba4181d0e2990f7c2848f09b1a6/src/components/textfield/TextField.js#L21

This doesn't match their typescript types either, but at least it should be easy enough to fix on our end.
