### ISSUE TITLE
Objects API "contract" feature - release blockers

### ISSUE THREAD

**Issue by sergei-maertens** [open-formulieren/open-forms#4019]
Follow up from #3688, these aspects should land in the 2.6 release

- [x] Handling of file fields - a file component (single or multiple uploads) should be possible to explicitly map to a particular (nested) property in the object type definition. Currently all upload fields are processed and result in an array of Documenten API urls, and it's not possible to match which component/file upload matches to which URL. We have the means now to work with structured data, this would be an unfortunate omission.
- [x] Document how one would use a "productaanvraag" user-defined variable and map that into the structure. This facilitates migrating from v1 to v2
- [x] Check if we can replace the payment status PATCH call with a PUT call instead (payment related variables need to be mappable)

**Comment by Viicos** [comment]
For the first checkbox:

- File upload components will be special cased during registration. This part of the code should be adapted:

https://github.com/open-formulieren/open-forms/blob/c963f22309102360ede0799b6473a8d5ac0d49db/src/openforms/registrations/contrib/objects_api/submission_registration.py#L333-L350

- Because we only offer compatible target paths to the user (e.g. when configuring the mapping for a `textfield` component, only the JSON Schema targets of `{"type": "string"}` will be offered in the UI), we have to special case this compatibility logic:
  - the `fileupload` component is of datatype `array`, but when registered, we will deal with the Documents URL (of datatype `string`). The admin frontend is the one providing a JSON Schema matching a variable, and requests the backend for a list of target paths compatible with such a JSON Schema. So this code will have to be adapted:
https://github.com/open-formulieren/open-forms/blob/1bbaeed3bfa5e239bf087ffc3641518c27a76ed4/src/openforms/js/components/admin/form_design/registrations/objectsapi/utils.js#L49-L60
  - Maybe the variables tab should display `datatype: string` instead of `datatype: array` in the `datatype` column? To make things less confusing
