### ISSUE TITLE
(wip) mapping: add possibility to select the same path for multiple registrations

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#4037]
### Thema / Theme

Form designer

### Omschrijving / Description

**Placeholder - Needs more thought/testing**

As a form designer i want to be able to create a mapping for multiple registration options with simple check boxes instead of having to select each path from a modal. 
This will simplify the task of mapping the variables.

Current solution:
![image](https://github.com/open-formulieren/open-forms/assets/112621537/55fe402a-8c47-41eb-ab8d-0d04f1ae1477)

Desired solution:
![image](https://github.com/open-formulieren/open-forms/assets/112621537/63366aa2-5160-4bbf-a09d-5cb8ba541c7b)

This enhancement is purely for form builders, and does not take into consideration the potential issues schema's being different in the other registration environments. But this could help identify these issues(?)

**Comment by sergei-maertens** [comment]
I have a reference schema with a dropdown having 50+ options - there was already a request for a search function in the dropdown from DH.

I don't think the suggested checkbox approach is going to create a pleasant UI when there are many options.

I also feel that the underlying issue here is not configuring multiple registration backends, but the bigger topic of how to bring configuration/forms from test -> acc -> prod :thinking:

**Comment by joeribekker** [comment]
Refinement: This is caused by the specific use case that DH is using to define seperate registration backends for separate environments. This use case is NOT how we intended this feature - So I don't want to do this.
