### ISSUE TITLE
When wait for payment is enabled, payment update notification e-mail is ignored. 

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#4334]
### Product versie / Product version

2.5.7

### Customer reference

RID: 196
NOPOLDER: 96
HADM: 101

### Omschrijf het probleem / Describe the bug

![image](https://github.com/open-formulieren/open-forms/assets/112621537/8e9b7465-7e6f-4b59-b69b-1b6b242bda64)
When in general settings the "Wait for payment to register" is checked, the email assiciated with payment updates (2) is not used. Instead the default adres (1) is used. 

### Screen resolution

None

### Device

None

### OS

None

**Comment by joeribekker** [comment]
Refinement: Not sure if this is intentional or not, but we can make this work. If you don't want it, you simply clear the email field. If this option is enabled, simply sent the payment update when registration email is also sent.

**Comment by sergei-maertens** [comment]
I think the point is that no payment update event is triggered at all, it all goes through regular registration flow rather than registration + update.

Does this mean that even if the option to wait is enabled, you still expect two emails? One for the registration, one with the "upate", and then if the email is not filled out, we skip the "update" email? I thought it'd be nicer to just get one email notification (the registration + info that it's paid) rather than two emails that you have to correlate :thinking:

**Comment by LaurensBurger** [comment]
currently the users expect a unique e-mail for the billing dept. Even if only paid submission are submitted, the billing dept. needs to be informed about the status and perhaps should not receive all the submission data.
