### ISSUE TITLE
Co-sign e-mail configuration suggests breaking the template.

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#4350]
### Product versie / Product version

2.6.x

### Customer reference

Utrecht: 233

### Omschrijf het probleem / Describe the bug

Adding: "https://{{form_url}}" to the template, as the wysiwg editor suggests:
![image](https://github.com/open-formulieren/open-forms/assets/112621537/c57e35ee-8b4a-4998-bd94-c62a694e2498)
Will generate the following link:
```html 
https://https//open-forms.test.nl/co-sign?_start=1
```

**Comment by sergei-maertens** [comment]
The popup is still shown on latest (5a676460710af99620f2f1bfa8be95fddf5bd31d)

**Comment by sergei-maertens** [comment]
Diving into the TinyMCE source code this doesn't seem easily patched - the dialog is triggered because of a configuration option that was added in #1080. We can disable the warning entirely, but then actual URLs pasted like `www.example.com` will not get any protocol prefix.

Original PR: #1148

Docs: https://www.tiny.cloud/docs/tinymce/latest/url-handling/#link_assume_external_targets
