### ISSUE TITLE
Allow the SDK to handle 403 permission denied responses for the `Submission` create endpoint if the Object does not belong to the user

### ISSUE THREAD

**Issue by stevenbal** [open-formulieren/open-forms#4399]

**Comment by vaszig** [comment]
Double checked this and the SDK already handles the `PermissionDenied` (403), since when we create the submission we do a try catch for the above exception. We have a message (_Je hebt geen toestemming om deze actie uit te voeren_) shown, so for now this can be considered as done. The proper error message for an object which does not belong to the user will be defined along with a future task, since we do not know yet the exact exception that we will raise from this check in the backend.
