### ISSUE TITLE
Block going to next step, also affects previous step?

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#4579]
### Product versie / Product version

2.6.13

### Customer reference

Taiga Hoorn 37

### Omschrijf het probleem / Describe the bug

Je kunt na een keuze / waarde ervoor zorgen dat je niet verder mag gaan door: blokkeer doorgang naar volgende stap.

Hiervoor moet je aangeven dat dat blokkeren pas ingaat als je in een bepaald stap komt.

Maar als je terug gaat naar de Vorige stap (Uw gegevens) wordt de button daar geblokkeerd. 
Waarschijnlijk omdat je al bij Aanvraag bent geweest. Het werkt blijkbaar niet vanaf Aanvraag

Heb van alles geprobeerd om dit op te heffen, maar het lukt mij niet om dit te de-blokeren.

### Screen resolution

None

### Device

None

### OS

None

**Comment by sergei-maertens** [comment]
Refinement: likely related to the `triggerFromStep` optional constraint on a logic rule, where the detection of the "current" step is broken (looking at the most recent completed step rather than the step that is firing the logic check).

**Comment by joeribekker** [comment]
Refinement: We will probably need to discuss this and scenarios to see what happens and what people expect to happen.

**Comment by stevenbal** [comment]
Discussed with Sergei: I'll try to reproduce this and check if the `inschakelen vanaf stap` logic is a workaround for this issue. If it is, we could add a ValidationError to ensure that `block going to the next step` requires `inschakelen vanaf stap` to be set

![image](https://github.com/user-attachments/assets/e02fefd8-1eca-477b-8e25-2ccdc4714ca5)

**Comment by stevenbal** [comment]
@sergei-maertens I checked this locally with the form from Hoorn, in their logic a user defined variable is set to `"nee"` based on input from step 1

![image](https://github.com/user-attachments/assets/57eefb72-0508-49d5-a3e8-7f2960a2926e)

and then in step 2 if this userdefined variable is `"nee"` (and the step is reached), the next step is blocked

![image](https://github.com/user-attachments/assets/8fca5e5f-dfe6-4dc2-a7b3-12c9a723f515)

which does mean that you cannot go to the next step anymore, because the step is considered reached if you reach it once and the variable can only be modified when going to the next step. 

I'm not sure if this kind of logic is commonplace (setting a variable based on values from the previous step), but I think you're right that determining the current step in the logic is not working as it should
