### ISSUE TITLE
Allow form URL-parameter to safely influence to which email address a submission is sent to

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#4650]
### Thema / Theme

Backend

### Omschrijving / Description

**Reference**: Taiga DB-52

1. A form-link contains a URL-param that holds an ID (example: `myform?destEmailID=78d6f1ab331`
2. The form variabele `destEmailID` is used to retrieve the `name` and actual `email address` via service fetch
3. The form shows only the `name` belonging to `destEmailID`
4. The submission is sent to the `email address` belonging to `destEmailID`

2 tasks are identified to make this scenario possible.

* [ ] Allow specific URL-parameters to be set as (form) variabele (ie. mark variabele as settable via URL-param)
* [ ] Allow sending the registration email to be sent to a variabele (being an email address ofcourse)

### Added value / Toegevoegde waarde

Allow mailing a predefined list of people via a form without exposing their email address.

**Comment by joeribekker** [comment]
Estimated on 4 weeks

**Comment by sergei-maertens** [comment]
> Allow specific URL-parameters to be set as (form) variabele (ie. mark variabele as settable via URL-param)

How are you going to avoid clashes with reserved URL parameter names, like we have `_start` and `initial_data_reference`, `time`, `submission_uuid`, `product`, `of-auth-problem`, `_digid-message`, `_eherkenning-message`, `_eidas-message` & `code`? Those are currently in use, but I'm more worried about developers being limited to adding own/internal query parameters for application logic because it may affect forms/break their auto-populate if they happen to shadow a form variable like that, and those will be situations that will be cryptic to debug/reproduce.

I also see a problem that you cannot reliably make it work for all types of form variabels - how do you plan to initialize a repeating group (list of) item(s) from a query parameter? Or a nested object? Those are not simple primitive datastructures that are easily string-encoded in a query parameter.

If we're going to have to write code to implement this feature, can't we instead build on top of existing constructs we already have and buy more time to properly design a prepopulate-via-the-client feature? I mean relying on the `initial_data_reference` here.
