### ISSUE TITLE
Expoints analytics causing CSP issues. 

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#4732]
### Product versie / Product version

2.7.x - 2.8.x

### Customer reference

hrlmmr 181

### Omschrijf het probleem / Describe the bug

At the moment it's not possible to enable Expoints because of the CSP issues it causes. 
It blocks loading of "local" scripts content/scripts (which can be solved by manually adding them to the csp rules) but also causes:

`Refused to execute inline script because it violates the following Content Security Policy directive: "script-src-elem https://*.expoints.nl open-forms.test.nl". Either the 'unsafe-inline' keyword, a hash ('sha256-M3vO32MFg1tJwV0zTnknLZG946q7lntoSxRkicfjyRg='), or a nonce ('nonce-...') is required to enable inline execution.`

### Stappen om te reproduceren / Steps to reproduce

enable Expoints in our test env

**Comment by stevenbal** [comment]
I'm not sure if the CSP error is what causes this, since I get that error at the form start and regardless of whether Expoints is enabled or not. I tried this locally and it seems that (at least as of right now) the Expoints server isn't responding (https://haarlemmermeer1.expoints.nl/m/Scripts/dist/expoints-external-loader.min.js for instance is giving timeouts for me).

I'll look into this later when Expoints is responsive again

**Comment by stevenbal** [comment]
I checked this again just now (from home) and now I can reach the URL, so it might be a firewall issue at the office? In any case, I tested a bit on the test environment and it seems that the CSP directives that are added when enabling expoints (`connect-src` and `script-src-elem`) override current behavior that relies on `default-src`, so when I'm working on Open Forms again next week I will pick this up

**Comment by melanievandenberg** [comment]
Volgens mij zou deze in release 2.8.1. meegaan, maar zie hem niet in de changelog. Schuift-ie weer door? @joeribekker
