### ISSUE TITLE
Add support for Admin-OIDC configuration via django-setup-configuration

### ISSUE THREAD

**Issue by sjoerdie** [open-formulieren/open-forms#4788]
### Thema / Theme

Frontend

### Omschrijving / Description

Add django-setup-configuration to configure admin OIDC for openforms

**Comment by stevenbal** [comment]
@sergei-maertens I thought a bit about this and here are my thoughts, let me know what you think:

- If I'm correct, all that is needed to configure the Objects API registration backend is part of the `ObjectsAPIGroupConfig` model
- I don't think it makes a lot of sense to split the configuration of Objecten and Objecttypen (and probably also Documenten and Catalogi), since they are also coupled in the `ObjectsAPIGroupConfig` model. So I would probably group that configuration in a single fixture (as well as the underlying Services probably?)
- Using environment variables to configure this doesn't seem like a good solution, because it should be possible to configure any amount of `ObjectsAPIGroupConfig`. I suppose we could add an envvar that points to a fixture (.yaml/.json) and load that in the `ConfigurationStep`. It does feel like setup-configuration is just a layer on top of `loaddata` then, but I suppose if you include it as a regular fixture there is no way to control when the data will be loaded, while with setup_configuration you deliberately use the command to do so
- We should probably add a simple command to easily create the fixture (which should use natural keys)
