### ISSUE TITLE
Case of select boxes values changed when step is never applicable during submission

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#4810]
### Product versie / Product version

2..8.1

### Customer reference

DH

### Omschrijf het probleem / Describe the bug

When a step is non-applicable from the start of the form and never made applicable, the select box component in this step (mapped with objecttype v2) submits values that are different from what can be seen in the form builder:
![image](https://github.com/user-attachments/assets/285a3d0d-d4e9-404b-88c5-116a23cdd053)
![image](https://github.com/user-attachments/assets/dbfd0acd-abca-4fb3-a765-30d6aefca72a)

This does not occur when the step is applicable. 
One submission with 2 identical components in different steps can produce this result: 
```json
                "stap-uno": {
                    "ditZijnCheckboxes": {
                        "HOOFDLETTERS": true,
                        "IS_IN_HOOFDLETTERS": true,
                        "JAWEL_SCREAMING_SNAKES": false
                    }
                },
                "stap-dos": {
                    "ditZijnCheckboxes1": {
                        "hoofdletters": false,
                        "is_in_hoofdletters": false,
                        "jawel_screaming_snakes": false
                    }
                }
```

Which causes issues with jsonschema validation.

**Comment by robinmolen** [comment]
Update: this happens because of the initial_value of the component form variable.

When submitting the form, a check is performed to make sure that all variables are present. (As i understand, to make sure that systems cannot break because of missing data). So when the component should be created, the data is collected from the initial_value of the form variable. For some reason this is (always) lowercase, resulting in lowercase data in the submission.
