### ISSUE TITLE
error on PUT to /api/v2/forms/{uuid_or_slug}/variables issues (investigating)

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms#4824]
### Product versie / Product version

2.7.x and higher (reproduced on our test env)

### Omschrijf het probleem / Describe the bug

Seeing cases where errors while saving a form ("variables") lead to a form where no input will be stored in de submission for the new variables. 

This can bee seen in the form itself as navigating back to these steps will simply show empty fields that previously held data. 
These specific variables are also missing in the variables tab of the form. 

These variables are "present" in the form builder, they also show in the front-end of the form but they are missing in the submission, and consequently trigger a validation error if they are required. 

This is either showing up more frequent now because of BE validation, or 2.7 introduced a bug where saving of variables has changed?

suspected ValidationErrors look something like this
`
[{}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {'key': [ErrorDetail(string='Ongeldige componentvariabele: er bestaat geen component met de opgegeven sleutel in de formulierdefinitie.', code='invalid')]}, {'key': [ErrorDetail(string='Ongeldige componentvariabele: er bestaat geen component met de opgegeven sleutel in de formulierdefinitie.', code='invalid')]}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}]
`
This would suggest this form now contains 2 "ghost" variables that unless refreshed by the from builder and saved again, will be missing from every submission

maykin-test form 608 is currently in this state - it contains 2 fields "dummyveld" and "dummyveld1" these were added with a "bad" component that triggered a error. 

Both fields show up in the form designer and front-end, but are not present when creating a submission. 

### Screen resolution

None

### Device

None

### OS

None

**Comment by stevenbal** [comment]
@LaurensBurger is the form with ID 608 the right one? I see many more fields in that one and no `dummyveld` or `dummyveld1`:

![image](https://github.com/user-attachments/assets/78cc4c58-2f59-4554-a931-c17972f47119)

Also if I save the form I get a different error than the one you got:
```rest_framework.exceptions.ValidationError: [{}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {'name': [ErrorDetail(string='This field may not be blank.', code='blank')]}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}]```

**Comment by LaurensBurger** [comment]
@stevenbal sorry I've messed a bit with it in the meantime - i'll bring it back to the original state. 

The error is just a way to trigger the state, looking at Sentry there are many ways to trigger it - i used the "softRequiredErrors" to trigger the state, but most form builders have the error from my original report.

**Comment by stevenbal** [comment]
I am now able to reproduce this locally with the database dump

@LaurensBurger for my understanding, the issue here is that when the form is in this broken state, you're not able to go to the next step, right? If I "fix" the form by removing the `softRequiredErrors`, the two variables you mentioned (dummy and dummy1) are only added once the step is completed. @sergei-maertens I'm not sure if this is the expected behavior, that when starting the form, the only `SubmissionValueVariables` that are created are user defined variables and that the component variables are created once each step is completed?

**Comment by stevenbal** [comment]
I've been able to reproduce this reliably:

1. add a new component to a form
2. go to the variables tab and add a User defined variable without adding a name (or any other way to trigger variable errors)
3. save the form (with errors)

Because the component was newly added, no variable existed for it yet and because of the validation errors on the variables endpoint, no new variable is created either. The formdefinition is already saved though, so it does appear in the form.

I'm not sure what would be the correct way to fix this, I don't think it'd be possible/desired to roll back the form definition with the added component because the variable tab fails. We could automatically put the form into maintenance mode until the errors are resolved (thinking out loud here)? 

I guess we could at least add a check to the email digest that detects forms for which there are missing formvariables, to make sure that it is clear that these need attention

**Comment by stevenbal** [comment]
Discussed with Sergei: ideally we would fix this by having a single API endpoint for the entire form + formsteps + variables etc., but this is a big refactor that would be an epic. For now we will go for a band aid solution by scheduling the task that ensures creation of FormVariables for components when the FormSteps are saved, this way the variables will be created regardless of errors when making requests to the variables endpoint

Also created a separate issue for the softRequiredErrors raising errors: https://github.com/open-formulieren/open-forms/issues/4884
