### ISSUE TITLE
Als burger/bedrijf wil ik kunnen inloggen met eIDAS

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#505]
Afgesplitst van #288 

**Verduidelijking nodig**

- [x] Moet hier nog iets speciaal voor gebeuren, anders dan de e-Herkenning koppeling met brokers? Dit gaat er van uit dat de e-Herkenningbrokers ook eIdas aanbieden.

In contact met iWelcome betreft het hetzelfde proces als e-Herkenning. eIDAS is toevoegd aan onze testaccount.
Er zijn 2 extra attributen in het metadata XML bestand nodig:

![Screenshot 2021-07-21 at 13 23 33](https://user-images.githubusercontent.com/96970/126508936-ab7c3dc1-fb6e-4b69-8eb0-1a8ffa2c7fce.png)

Het is me onduidelijk of 1 metadata bestand voldoende is voor zowel e-Herkenning als eIDAS zolang die 2 attributen er ook maar in zitten; of dat ze er echt 2 moeten hebben. iWelcome supportafdeling kan dit aangeven.

**Comment by SilviaAmAm** [comment]
After discussion with iWelcome, a new `ServiceDescription` and `ServiceInstance` were added to the dienstcatalogus. The `ServiceDescription` contains only the `<esc:EntityConcernedTypesAllowed>urn:etoegang:1.9:EntityConcernedID:Pseudo</esc:EntityConcernedTypesAllowed>` attribute, because apparently `eIDASLegalIdentifier` doesn't work yet. 

Since now there are 2 services in the dienstcatalogus, when a `AuthnRequest` is made to the broker, one should specify the `ServiceID` to determine whether it will be a eHerkenning or a eIDAS flow. I don't know yet how the ServiceID should be specified.

According to [this manual](https://www.vngrealisatie.nl/sites/default/files/2020-09/Handleiding_eIDAS1.01.pdf) (section 3.1), 
it seems that the response from eIDAS would at least contain this data:
1.  Huidige familienaam of familienamen 
2.  Huidige voornaam of voornamen  
3.  Geboortedatum  
4.  Uniek identificatienummer (let op: geen BSN)

If this is the case, then we need to add this unique identifier to the session in the same way as the DigiD plugin adds the BSN and the eHerkenning plugin adds the KvK.
