### ISSUE TITLE
Appointment improvements

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#597]
To prevent reloading and offer a better user experience, on the frontend:

* [x] Load products upon form step loading, instead of when clicking the pulldown.
* [x] Load locations in the dropdown upon selecting a product.
* [x] Load dates upon selecting a location.
* [x] Load times when a date is selected.
* [x] Whenever nothing is loaded, make the form elements disabled. Also make them disabled when the load is in progress.

Front end summary page

* [x] Should have human readable values in summary page.  Will need a way to save these human readable values after they have been selected.

In the admin:

* [x] Optimize the layout when designing a form, by making the checkboxes into a radio-select or dropdown (only one can be choosen anyway). Only show the additional fields when the appropriate option is selected.
* [x] Move appointment-specific configuration to separate tab #612

Submission:

* [x] ~~When an appointment cannot be made, the form should NOT be submitted. Instead the API should return an error message instead. The form then goes back to the summary page showing the error message to the user. Tracked in #614 - the SDK will poll a status endpoint which will relay the information.~~

**Comment by sergei-maertens** [comment]
Was typing out an issue and then remembered this one.

---

While testing the appointments on https://open-forms.test.maykin.opengem.nl/registratie-open-bedrijven-dag, I observed the following quirks (on Brave browser, which is essentially Chromium):

- [ ] The initial load of products was slow (3.3s, I presume because of WSDL loading/fetching). Subsequent loads were reasonably fast (250ms)
- [ ] When clicking a dropdown, it looks like the options are refreshed and it closes/re-opens or re-renders. It's not a pleasant user experience
- [ ] On the overview page, the appointment details are rendered weirdly:
    - Date is displayed in `YYYY-MM-DD`, this should be localized as `DD-MM-YYYY` or `<day> <month>, <year>` in a more textual form
    - Time is displayed in ISO-8601 - this should probably be restrict to just the time in `HH:mm` format
    - Product is just the product code
    - Location is the ID (?) of the location rather than the label.

**Comment by sergei-maertens** [comment]
Still working on the SDK parts

**Comment by sergei-maertens** [comment]
SDK part merged, it's not great in the total result atm, but we're following up in #682
