### ISSUE TITLE
Appointments field required validation is buggy

### ISSUE THREAD

**Issue by sergei-maertens** [open-formulieren/open-forms#633]
When I add a field to the form for appointments (e.g. location selection) and mark it as required in the "validation" tab, then the SDK displays a validation error even though a value was selected.

**Comment by shea-maykinmedia** [comment]
I took a quick look at this since I was working on the same code for another ticket but I'm not able to replicate this bug.  Can we take a look together when you have time?

I'll get the validation error if I try to submit or clear data when it's required but once I select a value the validation error goes away.

**Comment by joeribekker** [comment]
Getest. Dit werkt naar behoren.
