### ISSUE TITLE
Email template add more forms

### ISSUE THREAD

**Issue by sjoerdie** [open-formulieren/open-forms#734]
This ticket was rewritten into 2 tasks to address the actual problem.

**Tasks**

* [x] Move email template model/admin to the react Form designers as a tab
* [x] Add general email template to the general configuration (similar to confirmation text)

**Original report**

email templates --> edit --> click "+" sign behind "formulier" (NOg een formulier openen) opens a pop up to create a new form. 
One would expect the ability to add another existing form.

![add_form_mail](https://user-images.githubusercontent.com/85243022/135119834-05f2dc57-4d4b-4677-9325-dcfce78954bb.png)

**Comment by joeribekker** [comment]
We should discuss this. The + is a Django admin feature but the question is probably more like "why can't i connect more forms to the same email template"

**Comment by sjoerdie** [comment]
This request was initiated by Township Venray.

**Comment by sergei-maertens** [comment]
E-mail template set-up should probably also be integrated in the form editor as a separate tab rather than be its own page/resource to manage.

**Comment by shea-maykinmedia** [comment]
Since I'm going on vacation I wanted to give a quick summary of the progress on this ticket in case anyone else picks it up.  You can see what is done here: https://github.com/open-formulieren/open-forms/pull/821

The two tasks left are:
1. Making the react tab in the admin to set this.  The api serializer has been updated so the react code should be able to already interact by api.
2. We probably want some unit tests around the code, specifically testing that the default email is sent when the checkbox is not clicked.  I wrote some around the changes to the api but haven't written ones for the other code changes.
