### ISSUE TITLE
Fix list of auth plugins

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#805]
Please adjust these plugins:

- Demo BSN (test) -- Please mark as "biedt BSN aan", and unmark as test-plugin)
- Demo KvK-nummer (test) -- Please mark as "biedt KvK aan", and unmark as test-plugin)

The reason: These plugins are needed for normal testing by admins. The other ones can remain marked as test because they are for edge case testing.

**Comment by sergei-maertens** [comment]
#805 explicitly made us mark some demo/test plugins as "not-demo", which makes it they can be used by non-staff users. This ticket requires us to mark them as demo again, which contradicts the original ticket.

In my opinion, undoing #805 is fine, since demo plugins can be enabled via the feature flags for testing. And with #1384, it's possible to enable demo plugins through the feature flag, and disable a subset of them.
