### ISSUE TITLE
Invullen veld tijd werkt niet goed

### ISSUE THREAD

**Issue by alextreme** [open-formulieren/open-forms#878]
Taiga issue 141 (zie issue voor voorbeeldformulier):

Het invullen van een tijdstip werkt niet goed. Dit lijkt een logica refresh dingetje...

**Comment by sergei-maertens** [comment]
cause of janky fields (like currency, time and perhaps also the file inputs) is that we currently act on form value changes from FormIO, record those in our own local state and then pass down the values back to the react-formio component, which is causing the Formio components to rebuild/re-attach. it tries its best setting the cursor appropriately, but it doesn't go well.
I will try to find a solution so that we only pass the submission data once, if we're loading an existing step, rather than making this declaratively and track the form values state exclusively in FormIO - which may lead to other bugs and it's going to be fun if values change because of logic updates

I'm 99% sure that this ticket and #876 have the same cause
