### ISSUE TITLE
When registration backend is set to email but no email is filled in, the form does not give an error but is not saved

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#936]
Logs do show this error:
```
{'registration_backend_options': {'to_emails': [ErrorDetail(string='Dit veld is vereist.', code='required')]}}
```
but this error is not catched and shown to the user. The form appears to save but it does not...

See also #1036

**Comment by Bartvaderkin** [comment]
First thing I noticed in the current codebase it is not possible to create this situation: if I create a form and select the email backend but don't set the recipient email (`to_emails`) the form doesn't save but gives a red error indicator on the 'registratie' tab.

The problematic field is not highlighted and no error message is shown though (except the indicator on the tab).

**Comment by Bartvaderkin** [comment]
I tested with a demo registration plugin that raises Exception instead of RegistrationFailed and this fails the registration with a red "Er is iets foutgegaan bij het verzenden." on the summary view.

In the case of the RegistrationFailed the registration completes for the user (and on the backend enters the retry flow).

**Comment by joeribekker** [comment]
Ok, in that case we'll wait for the next report.
