### ISSUE TITLE
Confirmation email template renders newlines in email subject and raises error

### ISSUE THREAD

**Issue by Bartvaderkin** [open-formulieren/open-forms#964]
I created a new form and navigated the tabs while testing another thing, but I didn't enter anything in the confirmation tab.

On completion the celery task raised this from the `send_confirmation_email() task`:

    django.core.mail.message.BadHeaderError: Header values can't contain newlines (got '\n\n\n\nConfirmation of your Test Upload 4 submission\n\n' for header 'Subject')

I think the editor widget generates extra newlines? The subject needs a `.strip()` at least.

**Comment by joeribekker** [comment]
I noticed the same when translating. Will fix this.

**Comment by sergei-maertens** [comment]
Hrm, if I remember correctly the code calls `subject.strip()` before passing it to the mail functions :thinking: I did talk about this with @shea-maykinmedia

**Comment by shea-maykinmedia** [comment]
We do call `.strip()` when sending the "Form Saved" email here https://github.com/open-formulieren/open-forms/blob/master/src/openforms/submissions/api/serializers.py#L329 however it'd probably be better to call `strip()` just before sending the email.  Probably here https://github.com/open-formulieren/open-forms/blob/master/src/openforms/utils/email.py#L28

That said `strip()` only removes newlines from the beginning and end of a string while we probably also want to remove any in the entire string since we know we can't have newlines in a email subject.

Maybe something like `subject.replace("\n", "")`?

**Comment by sergei-maertens** [comment]
Right, newlines in the middle are a problem. Tbf, the default templates should just not put the templatetags on separate lines but join them all together, as discussed earlier.
