### ISSUE TITLE
When registration fails, no error is shown in the SDK

### ISSUE THREAD

**Issue by joeribekker** [open-formulieren/open-forms#980]
Tested with Microsoft Graph registration plugin. The user is redirected back to the overview page without any message.
The submission shows (in the admin) as failed.

**Comment by sergei-maertens** [comment]
Re-opening this one for a bit longer since I believe the process was designed to not crash hard, but still show the confirmation page as the submission is properly received _for us_.

The retry flow should then attempt to register with the failing backend again automatically, but this is invisible to the end-user.
